#!/usr/bin/env bash
set -euo pipefail

ROCKETMQ_BROKER_CONTAINER="${ROCKETMQ_BROKER_CONTAINER:-rmqbroker}"
ROCKETMQ_NAMESRV="${ROCKETMQ_NAMESRV:-rmqnamesrv:9876}"
ROCKETMQ_CLUSTER="${ROCKETMQ_CLUSTER:-DefaultCluster}"
ROCKETMQ_GROUP="${ROCKETMQ_GROUP:-matching-service}"
ROCKETMQ_DEPOSIT_TOPIC="${ROCKETMQ_DEPOSIT_TOPIC:-match_deposit}"
ROCKETMQ_WITHDRAW_TOPIC="${ROCKETMQ_WITHDRAW_TOPIC:-match_withdraw}"
ROCKETMQ_MAIN_QUEUE_NUM="${ROCKETMQ_MAIN_QUEUE_NUM:-8}"
ROCKETMQ_SYSTEM_QUEUE_NUM="${ROCKETMQ_SYSTEM_QUEUE_NUM:-1}"
ROCKETMQ_MAX_RECONSUME_TIMES="${ROCKETMQ_MAX_RECONSUME_TIMES:-16}"
ROCKETMQ_HOME="${ROCKETMQ_HOME:-/home/rocketmq/rocketmq-5.3.2}"

# mqadmin 在 RocketMQ broker 容器内执行。
mqadmin() {
	docker exec "${ROCKETMQ_BROKER_CONTAINER}" sh -lc "cd ${ROCKETMQ_HOME}/bin && ./mqadmin $*"
}

mqadmin updateSubGroup -n "${ROCKETMQ_NAMESRV}" -c "${ROCKETMQ_CLUSTER}" -g "${ROCKETMQ_GROUP}" -q "${ROCKETMQ_SYSTEM_QUEUE_NUM}" -r "${ROCKETMQ_MAX_RECONSUME_TIMES}" -o true -s true
mqadmin updateTopic -n "${ROCKETMQ_NAMESRV}" -c "${ROCKETMQ_CLUSTER}" -t "${ROCKETMQ_DEPOSIT_TOPIC}" -r "${ROCKETMQ_MAIN_QUEUE_NUM}" -w "${ROCKETMQ_MAIN_QUEUE_NUM}"
mqadmin updateTopic -n "${ROCKETMQ_NAMESRV}" -c "${ROCKETMQ_CLUSTER}" -t "${ROCKETMQ_WITHDRAW_TOPIC}" -r "${ROCKETMQ_MAIN_QUEUE_NUM}" -w "${ROCKETMQ_MAIN_QUEUE_NUM}"
mqadmin updateTopic -n "${ROCKETMQ_NAMESRV}" -c "${ROCKETMQ_CLUSTER}" -t "%RETRY%${ROCKETMQ_GROUP}" -r "${ROCKETMQ_SYSTEM_QUEUE_NUM}" -w "${ROCKETMQ_SYSTEM_QUEUE_NUM}"
mqadmin updateTopic -n "${ROCKETMQ_NAMESRV}" -c "${ROCKETMQ_CLUSTER}" -t "%DLQ%${ROCKETMQ_GROUP}" -r "${ROCKETMQ_SYSTEM_QUEUE_NUM}" -w "${ROCKETMQ_SYSTEM_QUEUE_NUM}"
