// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "time"

const TableNameDepositOrder = "deposit_order"

// DepositOrder 入金单
type DepositOrder struct {
	ID              int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:自增主键" json:"id"`                                                       // 自增主键
	DepositNo       string    `gorm:"column:deposit_no;type:varchar(64);not null;uniqueIndex:uk_deposit_no,priority:1;comment:入金单号" json:"depositNo"`                   // 入金单号
	MerchantID      int64     `gorm:"column:merchant_id;type:bigint;not null;comment:商户ID" json:"merchantId"`                                                           // 商户ID
	Channel         string    `gorm:"column:channel;type:varchar(32);not null;index:idx_match_pool,priority:1;index:idx_amount,priority:1;comment:支付渠道" json:"channel"` // 支付渠道
	Currency        string    `gorm:"column:currency;type:varchar(16);not null;index:idx_match_pool,priority:2;index:idx_amount,priority:2;comment:币种" json:"currency"` // 币种
	Amount          int64     `gorm:"column:amount;type:bigint;not null;index:idx_amount,priority:3;comment:入金金额，最小货币单位" json:"amount"`                                 // 入金金额，最小货币单位
	Status          int32     `gorm:"column:status;type:tinyint;not null;index:idx_match_pool,priority:3;comment:状态：1待撮合 2已锁定 3已撮合 4失败 5过期" json:"status"`              // 状态：1待撮合 2已锁定 3已撮合 4失败 5过期
	ExpireAt        time.Time `gorm:"column:expire_at;type:datetime(3);not null;index:idx_match_pool,priority:4;comment:过期时间" json:"expireAt"`                          // 过期时间
	MatchedBasketNo string    `gorm:"column:matched_basket_no;type:varchar(64);comment:匹配到的出金篮子单号" json:"matchedBasketNo"`                                              // 匹配到的出金篮子单号
	MatchNo         string    `gorm:"column:match_no;type:varchar(64);index:idx_match_no,priority:1;comment:撮合结果单号" json:"matchNo"`                                     // 撮合结果单号
	CreatedAt       time.Time `gorm:"column:created_at;type:datetime(3);not null;default:CURRENT_TIMESTAMP(3);comment:创建时间" json:"createdAt"`                           // 创建时间
	UpdatedAt       time.Time `gorm:"column:updated_at;type:datetime(3);not null;default:CURRENT_TIMESTAMP(3);comment:更新时间" json:"updatedAt"`                           // 更新时间
}

// TableName 返回 DepositOrder 对应的表名。
func (DepositOrder) TableName() string {
	return TableNameDepositOrder
}
