// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "time"

const TableNameStateLog = "match_state_log"

// StateLog 撮合状态流水
type StateLog struct {
	ID         int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:自增主键" json:"id"`                                                                                                  // 自增主键
	BizNo      string    `gorm:"column:biz_no;type:varchar(64);not null;index:idx_biz_no,priority:1;comment:业务单号" json:"bizNo"`                                                                               // 业务单号
	BizType    string    `gorm:"column:biz_type;type:varchar(32);not null;index:idx_biz_type_status,priority:1;comment:业务类型：deposit/basket/match/payment" json:"bizType"`                                     // 业务类型
	FromStatus *int32    `gorm:"column:from_status;type:tinyint;comment:原状态" json:"fromStatus"`                                                                                                               // 原状态
	ToStatus   int32     `gorm:"column:to_status;type:tinyint;not null;index:idx_biz_type_status,priority:2;comment:新状态" json:"toStatus"`                                                                     // 新状态
	Reason     string    `gorm:"column:reason;type:varchar(128);comment:变更原因" json:"reason"`                                                                                                                  // 变更原因
	Operator   string    `gorm:"column:operator;type:varchar(64);comment:操作来源" json:"operator"`                                                                                                               // 操作来源
	CreatedAt  time.Time `gorm:"column:created_at;type:datetime(3);not null;default:CURRENT_TIMESTAMP(3);index:idx_biz_type_status,priority:3;index:idx_created_at,priority:1;comment:创建时间" json:"createdAt"` // 创建时间
}

// TableName 返回 StateLog 对应的表名。
func (StateLog) TableName() string {
	return TableNameStateLog
}
