// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"matching-service/internal/biz"
	"matching-service/internal/conf"
	"matching-service/internal/data"
	"matching-service/internal/server"
	"matching-service/internal/service"
	"matching-service/pkg/lock"
)

// Injectors from wire.go:

// newApplication 使用 Wire 装配服务依赖。
func newApplication(ctx context.Context, confPath string) (*application, error) {
	bootstrap, err := conf.Load(confPath)
	if err != nil {
		return nil, err
	}
	dataData, err := data.NewData(bootstrap)
	if err != nil {
		return nil, err
	}
	redisLock := lock.NewRedisLock(bootstrap)
	metrics := biz.NewMetrics()
	matchingUsecase, err := biz.NewMatchingUsecase(ctx, bootstrap, dataData, redisLock, metrics)
	if err != nil {
		return nil, err
	}
	matchingConsumer := service.NewMatchingConsumer(matchingUsecase, metrics)
	rocketMQConsumer := server.NewRocketMQConsumer(bootstrap, matchingConsumer)
	expireWorker := server.NewExpireWorker(bootstrap, matchingUsecase)
	healthChecker := server.NewHealthChecker(bootstrap, dataData, redisLock)
	matchingService := service.NewMatchingService(matchingUsecase, healthChecker)
	grpcServer := server.NewGRPCServer(bootstrap, matchingService)
	metricsServer := server.NewMetricsServer(bootstrap, metrics)
	mainApplication := &application{
		cfg:              bootstrap,
		data:             dataData,
		shardLock:        redisLock,
		rocketMQConsumer: rocketMQConsumer,
		expireWorker:     expireWorker,
		grpcServer:       grpcServer,
		metricsServer:    metricsServer,
	}
	return mainApplication, nil
}
