// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"

	"matching-service/internal/biz"
	"matching-service/internal/conf"
	"matching-service/internal/data"
	"matching-service/internal/server"
	"matching-service/internal/service"
	"matching-service/pkg/toolbox/redisx"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp 使用 Wire 装配 Kratos 应用。
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	confServer := bootstrap.Server
	context := provideContext()
	dataData, cleanup, err := data.NewData(bootstrap)
	if err != nil {
		return nil, nil, err
	}
	redisLock, cleanup2, err := redisx.NewShardLockProvider(bootstrap)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	metrics := biz.NewMetrics()
	matchingUsecase, err := biz.NewMatchingUsecase(context, bootstrap, dataData, redisLock, metrics)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	healthChecker := server.NewHealthChecker(bootstrap, dataData, redisLock)
	matchingService := service.NewMatchingService(matchingUsecase, healthChecker)
	grpcServer := server.NewGRPCServer(confServer, matchingService, logger)
	httpServer := server.NewMetricsServer(confServer, metrics)
	matchingConsumer := service.NewMatchingConsumer(matchingUsecase, metrics)
	consumerManager, err := server.NewConsumerManager(bootstrap, matchingConsumer, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	producer, err := server.NewMQProducer(bootstrap)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	expireWorker := server.NewExpireWorker(bootstrap, matchingUsecase)
	app := newApp(logger, grpcServer, httpServer, consumerManager, producer, expireWorker)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

func provideContext() context.Context {
	return context.Background()
}
