// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bootstrap 是服务启动配置根节点，对应 configs/config.yaml。
type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Match         *Match                 `protobuf:"bytes,3,opt,name=match,proto3" json:"match,omitempty"`
	Trace         *Trace                 `protobuf:"bytes,4,opt,name=trace,proto3" json:"trace,omitempty"`
	Sentry        *Sentry                `protobuf:"bytes,5,opt,name=sentry,proto3" json:"sentry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetMatch() *Match {
	if x != nil {
		return x.Match
	}
	return nil
}

func (x *Bootstrap) GetTrace() *Trace {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *Bootstrap) GetSentry() *Sentry {
	if x != nil {
		return x.Sentry
	}
	return nil
}

// Server 是对外服务监听配置。
type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grpc          *GRPC                  `protobuf:"bytes,1,opt,name=grpc,proto3" json:"grpc,omitempty"`
	Metrics       *Metrics               `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetGrpc() *GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

func (x *Server) GetMetrics() *Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// GRPC 是撮合 gRPC API 监听配置。
type GRPC struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 传输层协议，如 tcp；空则使用 Kratos 默认。
	Network string `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	// 监听地址，如 :9203。
	Addr string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	// 请求超时；空则不限。
	Timeout       *durationpb.Duration `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GRPC) Reset() {
	*x = GRPC{}
	mi := &file_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GRPC) ProtoMessage() {}

func (x *GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GRPC.ProtoReflect.Descriptor instead.
func (*GRPC) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{2}
}

func (x *GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

// Metrics 是 Prometheus 指标 HTTP 配置。
type Metrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 监听地址，路径固定 /metrics。
	Addr          string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Metrics) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

// Data 是 MySQL、Redis、RocketMQ 与 ORM 日志配置。
type Data struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Mysql    *MySQL                 `protobuf:"bytes,1,opt,name=mysql,proto3" json:"mysql,omitempty"`
	Redis    *Redis                 `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
	Rocketmq *RocketMQ              `protobuf:"bytes,3,opt,name=rocketmq,proto3" json:"rocketmq,omitempty"`
	// GORM 日志：silent | error | warn | info。
	GormLogLevel  string `protobuf:"bytes,4,opt,name=gorm_log_level,json=gormLogLevel,proto3" json:"gorm_log_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{4}
}

func (x *Data) GetMysql() *MySQL {
	if x != nil {
		return x.Mysql
	}
	return nil
}

func (x *Data) GetRedis() *Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

func (x *Data) GetRocketmq() *RocketMQ {
	if x != nil {
		return x.Rocketmq
	}
	return nil
}

func (x *Data) GetGormLogLevel() string {
	if x != nil {
		return x.GormLogLevel
	}
	return ""
}

// MySQL 连接配置。
type MySQL struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Driver string                 `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	// 完整 DSN，如 user:pass@tcp(host:3306)/db?parseTime=true。
	Source        string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MySQL) Reset() {
	*x = MySQL{}
	mi := &file_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MySQL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MySQL) ProtoMessage() {}

func (x *MySQL) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MySQL.ProtoReflect.Descriptor instead.
func (*MySQL) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{5}
}

func (x *MySQL) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *MySQL) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// Redis 连接配置，用于分片分布式锁。
type Redis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Db            int32                  `protobuf:"varint,3,opt,name=db,proto3" json:"db,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Redis) Reset() {
	*x = Redis{}
	mi := &file_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Redis) ProtoMessage() {}

func (x *Redis) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Redis.ProtoReflect.Descriptor instead.
func (*Redis) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{6}
}

func (x *Redis) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Redis) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Redis) GetDb() int32 {
	if x != nil {
		return x.Db
	}
	return 0
}

// RocketMQ 5.x 配置（非旧版 name_server）。
type RocketMQ struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Proxy/gRPC 端点 host:port。
	Endpoint      string    `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Namespace     string    `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	AccessKey     string    `protobuf:"bytes,3,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	AccessSecret  string    `protobuf:"bytes,4,opt,name=access_secret,json=accessSecret,proto3" json:"access_secret,omitempty"`
	DepositTopic  string    `protobuf:"bytes,5,opt,name=deposit_topic,json=depositTopic,proto3" json:"deposit_topic,omitempty"`
	WithdrawTopic string    `protobuf:"bytes,6,opt,name=withdraw_topic,json=withdrawTopic,proto3" json:"withdraw_topic,omitempty"`
	Consumer      *Consumer `protobuf:"bytes,7,opt,name=consumer,proto3" json:"consumer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RocketMQ) Reset() {
	*x = RocketMQ{}
	mi := &file_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RocketMQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RocketMQ) ProtoMessage() {}

func (x *RocketMQ) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RocketMQ.ProtoReflect.Descriptor instead.
func (*RocketMQ) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{7}
}

func (x *RocketMQ) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *RocketMQ) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RocketMQ) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *RocketMQ) GetAccessSecret() string {
	if x != nil {
		return x.AccessSecret
	}
	return ""
}

func (x *RocketMQ) GetDepositTopic() string {
	if x != nil {
		return x.DepositTopic
	}
	return ""
}

func (x *RocketMQ) GetWithdrawTopic() string {
	if x != nil {
		return x.WithdrawTopic
	}
	return ""
}

func (x *RocketMQ) GetConsumer() *Consumer {
	if x != nil {
		return x.Consumer
	}
	return nil
}

// RocketMQ 消费者配置。
type Consumer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Group string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	// 并发数；serial=true 时不使用线程池。
	WorkerNum int32 `protobuf:"varint,2,opt,name=worker_num,json=workerNum,proto3" json:"worker_num,omitempty"`
	// true 时串行消费，保证顺序语义。
	Serial        bool `protobuf:"varint,3,opt,name=serial,proto3" json:"serial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Consumer) Reset() {
	*x = Consumer{}
	mi := &file_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Consumer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Consumer) ProtoMessage() {}

func (x *Consumer) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Consumer.ProtoReflect.Descriptor instead.
func (*Consumer) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{8}
}

func (x *Consumer) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Consumer) GetWorkerNum() int32 {
	if x != nil {
		return x.WorkerNum
	}
	return 0
}

func (x *Consumer) GetSerial() bool {
	if x != nil {
		return x.Serial
	}
	return false
}

// Match 是撮合引擎与后台任务参数。
type Match struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 少发成交最低比例，万分比（3000=30%）。
	MinCompleteRate int64 `protobuf:"varint,1,opt,name=min_complete_rate,json=minCompleteRate,proto3" json:"min_complete_rate,omitempty"`
	// 入金默认 TTL（分钟），预留；实际以消息 expire_at 为准。
	DepositTtlMin int32 `protobuf:"varint,2,opt,name=deposit_ttl_min,json=depositTtlMin,proto3" json:"deposit_ttl_min,omitempty"`
	// 启动恢复活跃篮子上限。
	BasketLimit int32 `protobuf:"varint,3,opt,name=basket_limit,json=basketLimit,proto3" json:"basket_limit,omitempty"`
	// Redis 分片锁 TTL（秒）。
	ShardLockTtlSecond int32 `protobuf:"varint,4,opt,name=shard_lock_ttl_second,json=shardLockTtlSecond,proto3" json:"shard_lock_ttl_second,omitempty"`
	// 过期扫描周期（秒）。
	ExpireIntervalSec int32 `protobuf:"varint,5,opt,name=expire_interval_sec,json=expireIntervalSec,proto3" json:"expire_interval_sec,omitempty"`
	// 单次过期处理批量上限。
	ExpireBatchSize int32 `protobuf:"varint,6,opt,name=expire_batch_size,json=expireBatchSize,proto3" json:"expire_batch_size,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Match) Reset() {
	*x = Match{}
	mi := &file_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match) ProtoMessage() {}

func (x *Match) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match.ProtoReflect.Descriptor instead.
func (*Match) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{9}
}

func (x *Match) GetMinCompleteRate() int64 {
	if x != nil {
		return x.MinCompleteRate
	}
	return 0
}

func (x *Match) GetDepositTtlMin() int32 {
	if x != nil {
		return x.DepositTtlMin
	}
	return 0
}

func (x *Match) GetBasketLimit() int32 {
	if x != nil {
		return x.BasketLimit
	}
	return 0
}

func (x *Match) GetShardLockTtlSecond() int32 {
	if x != nil {
		return x.ShardLockTtlSecond
	}
	return 0
}

func (x *Match) GetExpireIntervalSec() int32 {
	if x != nil {
		return x.ExpireIntervalSec
	}
	return 0
}

func (x *Match) GetExpireBatchSize() int32 {
	if x != nil {
		return x.ExpireBatchSize
	}
	return 0
}

// Trace 是 OpenTelemetry 追踪导出（YAML 键 trace，无 opentelemetry 段）。
type Trace struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OTLP gRPC 地址（host:port）；空则不注册 TracerProvider。
	Endpoint string `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// OTLP 认证头 Authentication；ADOT/IRSA 通常为空。
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	// 采样比例 0~1。
	SampleRatio   float32 `protobuf:"fixed32,3,opt,name=sample_ratio,json=sampleRatio,proto3" json:"sample_ratio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trace) Reset() {
	*x = Trace{}
	mi := &file_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trace) ProtoMessage() {}

func (x *Trace) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trace.ProtoReflect.Descriptor instead.
func (*Trace) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{10}
}

func (x *Trace) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Trace) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Trace) GetSampleRatio() float32 {
	if x != nil {
		return x.SampleRatio
	}
	return 0
}

// Sentry 错误与 panic 上报，与 Trace 独立。
type Sentry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 项目 DSN；空则不上报。
	Dsn string `protobuf:"bytes,1,opt,name=dsn,proto3" json:"dsn,omitempty"`
	// 环境标签，如 dev / staging / prod。
	Env string `protobuf:"bytes,2,opt,name=env,proto3" json:"env,omitempty"`
	// 可选日志平台链接，纯 AWS 可留空。
	SlsAddr       string `protobuf:"bytes,3,opt,name=sls_addr,json=slsAddr,proto3" json:"sls_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sentry) Reset() {
	*x = Sentry{}
	mi := &file_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sentry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sentry) ProtoMessage() {}

func (x *Sentry) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sentry.ProtoReflect.Descriptor instead.
func (*Sentry) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{11}
}

func (x *Sentry) GetDsn() string {
	if x != nil {
		return x.Dsn
	}
	return ""
}

func (x *Sentry) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *Sentry) GetSlsAddr() string {
	if x != nil {
		return x.SlsAddr
	}
	return ""
}

var File_conf_proto protoreflect.FileDescriptor

const file_conf_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"conf.proto\x12\rmatching.conf\x1a\x1egoogle/protobuf/duration.proto\"\xea\x01\n" +
	"\tBootstrap\x12-\n" +
	"\x06server\x18\x01 \x01(\v2\x15.matching.conf.ServerR\x06server\x12'\n" +
	"\x04data\x18\x02 \x01(\v2\x13.matching.conf.DataR\x04data\x12*\n" +
	"\x05match\x18\x03 \x01(\v2\x14.matching.conf.MatchR\x05match\x12*\n" +
	"\x05trace\x18\x04 \x01(\v2\x14.matching.conf.TraceR\x05trace\x12-\n" +
	"\x06sentry\x18\x05 \x01(\v2\x15.matching.conf.SentryR\x06sentry\"c\n" +
	"\x06Server\x12'\n" +
	"\x04grpc\x18\x01 \x01(\v2\x13.matching.conf.GRPCR\x04grpc\x120\n" +
	"\ametrics\x18\x02 \x01(\v2\x16.matching.conf.MetricsR\ametrics\"i\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\x1d\n" +
	"\aMetrics\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\"\xb9\x01\n" +
	"\x04Data\x12*\n" +
	"\x05mysql\x18\x01 \x01(\v2\x14.matching.conf.MySQLR\x05mysql\x12*\n" +
	"\x05redis\x18\x02 \x01(\v2\x14.matching.conf.RedisR\x05redis\x123\n" +
	"\brocketmq\x18\x03 \x01(\v2\x17.matching.conf.RocketMQR\brocketmq\x12$\n" +
	"\x0egorm_log_level\x18\x04 \x01(\tR\fgormLogLevel\"7\n" +
	"\x05MySQL\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\"G\n" +
	"\x05Redis\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x0e\n" +
	"\x02db\x18\x03 \x01(\x05R\x02db\"\x89\x02\n" +
	"\bRocketMQ\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1d\n" +
	"\n" +
	"access_key\x18\x03 \x01(\tR\taccessKey\x12#\n" +
	"\raccess_secret\x18\x04 \x01(\tR\faccessSecret\x12#\n" +
	"\rdeposit_topic\x18\x05 \x01(\tR\fdepositTopic\x12%\n" +
	"\x0ewithdraw_topic\x18\x06 \x01(\tR\rwithdrawTopic\x123\n" +
	"\bconsumer\x18\a \x01(\v2\x17.matching.conf.ConsumerR\bconsumer\"W\n" +
	"\bConsumer\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x1d\n" +
	"\n" +
	"worker_num\x18\x02 \x01(\x05R\tworkerNum\x12\x16\n" +
	"\x06serial\x18\x03 \x01(\bR\x06serial\"\x8d\x02\n" +
	"\x05Match\x12*\n" +
	"\x11min_complete_rate\x18\x01 \x01(\x03R\x0fminCompleteRate\x12&\n" +
	"\x0fdeposit_ttl_min\x18\x02 \x01(\x05R\rdepositTtlMin\x12!\n" +
	"\fbasket_limit\x18\x03 \x01(\x05R\vbasketLimit\x121\n" +
	"\x15shard_lock_ttl_second\x18\x04 \x01(\x05R\x12shardLockTtlSecond\x12.\n" +
	"\x13expire_interval_sec\x18\x05 \x01(\x05R\x11expireIntervalSec\x12*\n" +
	"\x11expire_batch_size\x18\x06 \x01(\x05R\x0fexpireBatchSize\"\\\n" +
	"\x05Trace\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12!\n" +
	"\fsample_ratio\x18\x03 \x01(\x02R\vsampleRatio\"G\n" +
	"\x06Sentry\x12\x10\n" +
	"\x03dsn\x18\x01 \x01(\tR\x03dsn\x12\x10\n" +
	"\x03env\x18\x02 \x01(\tR\x03env\x12\x19\n" +
	"\bsls_addr\x18\x03 \x01(\tR\aslsAddrB%Z#matching-service/internal/conf;confb\x06proto3"

var (
	file_conf_proto_rawDescOnce sync.Once
	file_conf_proto_rawDescData []byte
)

func file_conf_proto_rawDescGZIP() []byte {
	file_conf_proto_rawDescOnce.Do(func() {
		file_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_proto_rawDesc), len(file_conf_proto_rawDesc)))
	})
	return file_conf_proto_rawDescData
}

var file_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),           // 0: matching.conf.Bootstrap
	(*Server)(nil),              // 1: matching.conf.Server
	(*GRPC)(nil),                // 2: matching.conf.GRPC
	(*Metrics)(nil),             // 3: matching.conf.Metrics
	(*Data)(nil),                // 4: matching.conf.Data
	(*MySQL)(nil),               // 5: matching.conf.MySQL
	(*Redis)(nil),               // 6: matching.conf.Redis
	(*RocketMQ)(nil),            // 7: matching.conf.RocketMQ
	(*Consumer)(nil),            // 8: matching.conf.Consumer
	(*Match)(nil),               // 9: matching.conf.Match
	(*Trace)(nil),               // 10: matching.conf.Trace
	(*Sentry)(nil),              // 11: matching.conf.Sentry
	(*durationpb.Duration)(nil), // 12: google.protobuf.Duration
}
var file_conf_proto_depIdxs = []int32{
	1,  // 0: matching.conf.Bootstrap.server:type_name -> matching.conf.Server
	4,  // 1: matching.conf.Bootstrap.data:type_name -> matching.conf.Data
	9,  // 2: matching.conf.Bootstrap.match:type_name -> matching.conf.Match
	10, // 3: matching.conf.Bootstrap.trace:type_name -> matching.conf.Trace
	11, // 4: matching.conf.Bootstrap.sentry:type_name -> matching.conf.Sentry
	2,  // 5: matching.conf.Server.grpc:type_name -> matching.conf.GRPC
	3,  // 6: matching.conf.Server.metrics:type_name -> matching.conf.Metrics
	12, // 7: matching.conf.GRPC.timeout:type_name -> google.protobuf.Duration
	5,  // 8: matching.conf.Data.mysql:type_name -> matching.conf.MySQL
	6,  // 9: matching.conf.Data.redis:type_name -> matching.conf.Redis
	7,  // 10: matching.conf.Data.rocketmq:type_name -> matching.conf.RocketMQ
	8,  // 11: matching.conf.RocketMQ.consumer:type_name -> matching.conf.Consumer
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_conf_proto_init() }
func file_conf_proto_init() {
	if File_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_proto_rawDesc), len(file_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_proto_goTypes,
		DependencyIndexes: file_conf_proto_depIdxs,
		MessageInfos:      file_conf_proto_msgTypes,
	}.Build()
	File_conf_proto = out.File
	file_conf_proto_goTypes = nil
	file_conf_proto_depIdxs = nil
}
