// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: api/matching/v1/matching.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MatchingService_CreateBasket_FullMethodName   = "/matching.v1.MatchingService/CreateBasket"
	MatchingService_SubmitDeposit_FullMethodName  = "/matching.v1.MatchingService/SubmitDeposit"
	MatchingService_ExpireTimeouts_FullMethodName = "/matching.v1.MatchingService/ExpireTimeouts"
	MatchingService_GetDeposit_FullMethodName     = "/matching.v1.MatchingService/GetDeposit"
	MatchingService_GetBasket_FullMethodName      = "/matching.v1.MatchingService/GetBasket"
	MatchingService_GetMatch_FullMethodName       = "/matching.v1.MatchingService/GetMatch"
	MatchingService_CheckHealth_FullMethodName    = "/matching.v1.MatchingService/CheckHealth"
	MatchingService_GetMetrics_FullMethodName     = "/matching.v1.MatchingService/GetMetrics"
)

// MatchingServiceClient is the client API for MatchingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MatchingService 是撮合服务的 gRPC 接口。
type MatchingServiceClient interface {
	// CreateBasket 创建出金撮合篮子。
	CreateBasket(ctx context.Context, in *CreateBasketRequest, opts ...grpc.CallOption) (*CreateBasketReply, error)
	// SubmitDeposit 提交入金单并尝试撮合。
	SubmitDeposit(ctx context.Context, in *SubmitDepositRequest, opts ...grpc.CallOption) (*SubmitDepositReply, error)
	// ExpireTimeouts 处理超时的入金单和出金篮子。
	ExpireTimeouts(ctx context.Context, in *ExpireTimeoutsRequest, opts ...grpc.CallOption) (*ExpireTimeoutsReply, error)
	// GetDeposit 查询入金单。
	GetDeposit(ctx context.Context, in *GetDepositRequest, opts ...grpc.CallOption) (*GetDepositReply, error)
	// GetBasket 查询出金撮合篮子。
	GetBasket(ctx context.Context, in *GetBasketRequest, opts ...grpc.CallOption) (*GetBasketReply, error)
	// GetMatch 查询撮合记录。
	GetMatch(ctx context.Context, in *GetMatchRequest, opts ...grpc.CallOption) (*GetMatchReply, error)
	// CheckHealth 检查服务依赖健康状态。
	CheckHealth(ctx context.Context, in *CheckHealthRequest, opts ...grpc.CallOption) (*CheckHealthReply, error)
	// GetMetrics 查询服务运行指标。
	GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsReply, error)
}

type matchingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchingServiceClient(cc grpc.ClientConnInterface) MatchingServiceClient {
	return &matchingServiceClient{cc}
}

func (c *matchingServiceClient) CreateBasket(ctx context.Context, in *CreateBasketRequest, opts ...grpc.CallOption) (*CreateBasketReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBasketReply)
	err := c.cc.Invoke(ctx, MatchingService_CreateBasket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchingServiceClient) SubmitDeposit(ctx context.Context, in *SubmitDepositRequest, opts ...grpc.CallOption) (*SubmitDepositReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitDepositReply)
	err := c.cc.Invoke(ctx, MatchingService_SubmitDeposit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchingServiceClient) ExpireTimeouts(ctx context.Context, in *ExpireTimeoutsRequest, opts ...grpc.CallOption) (*ExpireTimeoutsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExpireTimeoutsReply)
	err := c.cc.Invoke(ctx, MatchingService_ExpireTimeouts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchingServiceClient) GetDeposit(ctx context.Context, in *GetDepositRequest, opts ...grpc.CallOption) (*GetDepositReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDepositReply)
	err := c.cc.Invoke(ctx, MatchingService_GetDeposit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchingServiceClient) GetBasket(ctx context.Context, in *GetBasketRequest, opts ...grpc.CallOption) (*GetBasketReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBasketReply)
	err := c.cc.Invoke(ctx, MatchingService_GetBasket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchingServiceClient) GetMatch(ctx context.Context, in *GetMatchRequest, opts ...grpc.CallOption) (*GetMatchReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMatchReply)
	err := c.cc.Invoke(ctx, MatchingService_GetMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchingServiceClient) CheckHealth(ctx context.Context, in *CheckHealthRequest, opts ...grpc.CallOption) (*CheckHealthReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckHealthReply)
	err := c.cc.Invoke(ctx, MatchingService_CheckHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchingServiceClient) GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMetricsReply)
	err := c.cc.Invoke(ctx, MatchingService_GetMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatchingServiceServer is the server API for MatchingService service.
// All implementations must embed UnimplementedMatchingServiceServer
// for forward compatibility.
//
// MatchingService 是撮合服务的 gRPC 接口。
type MatchingServiceServer interface {
	// CreateBasket 创建出金撮合篮子。
	CreateBasket(context.Context, *CreateBasketRequest) (*CreateBasketReply, error)
	// SubmitDeposit 提交入金单并尝试撮合。
	SubmitDeposit(context.Context, *SubmitDepositRequest) (*SubmitDepositReply, error)
	// ExpireTimeouts 处理超时的入金单和出金篮子。
	ExpireTimeouts(context.Context, *ExpireTimeoutsRequest) (*ExpireTimeoutsReply, error)
	// GetDeposit 查询入金单。
	GetDeposit(context.Context, *GetDepositRequest) (*GetDepositReply, error)
	// GetBasket 查询出金撮合篮子。
	GetBasket(context.Context, *GetBasketRequest) (*GetBasketReply, error)
	// GetMatch 查询撮合记录。
	GetMatch(context.Context, *GetMatchRequest) (*GetMatchReply, error)
	// CheckHealth 检查服务依赖健康状态。
	CheckHealth(context.Context, *CheckHealthRequest) (*CheckHealthReply, error)
	// GetMetrics 查询服务运行指标。
	GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsReply, error)
	mustEmbedUnimplementedMatchingServiceServer()
}

// UnimplementedMatchingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMatchingServiceServer struct{}

func (UnimplementedMatchingServiceServer) CreateBasket(context.Context, *CreateBasketRequest) (*CreateBasketReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBasket not implemented")
}
func (UnimplementedMatchingServiceServer) SubmitDeposit(context.Context, *SubmitDepositRequest) (*SubmitDepositReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitDeposit not implemented")
}
func (UnimplementedMatchingServiceServer) ExpireTimeouts(context.Context, *ExpireTimeoutsRequest) (*ExpireTimeoutsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ExpireTimeouts not implemented")
}
func (UnimplementedMatchingServiceServer) GetDeposit(context.Context, *GetDepositRequest) (*GetDepositReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeposit not implemented")
}
func (UnimplementedMatchingServiceServer) GetBasket(context.Context, *GetBasketRequest) (*GetBasketReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBasket not implemented")
}
func (UnimplementedMatchingServiceServer) GetMatch(context.Context, *GetMatchRequest) (*GetMatchReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMatch not implemented")
}
func (UnimplementedMatchingServiceServer) CheckHealth(context.Context, *CheckHealthRequest) (*CheckHealthReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckHealth not implemented")
}
func (UnimplementedMatchingServiceServer) GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedMatchingServiceServer) mustEmbedUnimplementedMatchingServiceServer() {}
func (UnimplementedMatchingServiceServer) testEmbeddedByValue()                         {}

// UnsafeMatchingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchingServiceServer will
// result in compilation errors.
type UnsafeMatchingServiceServer interface {
	mustEmbedUnimplementedMatchingServiceServer()
}

func RegisterMatchingServiceServer(s grpc.ServiceRegistrar, srv MatchingServiceServer) {
	// If the following call panics, it indicates UnimplementedMatchingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MatchingService_ServiceDesc, srv)
}

func _MatchingService_CreateBasket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBasketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingServiceServer).CreateBasket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingService_CreateBasket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingServiceServer).CreateBasket(ctx, req.(*CreateBasketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchingService_SubmitDeposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitDepositRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingServiceServer).SubmitDeposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingService_SubmitDeposit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingServiceServer).SubmitDeposit(ctx, req.(*SubmitDepositRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchingService_ExpireTimeouts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExpireTimeoutsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingServiceServer).ExpireTimeouts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingService_ExpireTimeouts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingServiceServer).ExpireTimeouts(ctx, req.(*ExpireTimeoutsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchingService_GetDeposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDepositRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingServiceServer).GetDeposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingService_GetDeposit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingServiceServer).GetDeposit(ctx, req.(*GetDepositRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchingService_GetBasket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBasketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingServiceServer).GetBasket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingService_GetBasket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingServiceServer).GetBasket(ctx, req.(*GetBasketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchingService_GetMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingServiceServer).GetMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingService_GetMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingServiceServer).GetMatch(ctx, req.(*GetMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchingService_CheckHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingServiceServer).CheckHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingService_CheckHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingServiceServer).CheckHealth(ctx, req.(*CheckHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchingService_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingServiceServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingService_GetMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingServiceServer).GetMetrics(ctx, req.(*GetMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MatchingService_ServiceDesc is the grpc.ServiceDesc for MatchingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatchingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "matching.v1.MatchingService",
	HandlerType: (*MatchingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBasket",
			Handler:    _MatchingService_CreateBasket_Handler,
		},
		{
			MethodName: "SubmitDeposit",
			Handler:    _MatchingService_SubmitDeposit_Handler,
		},
		{
			MethodName: "ExpireTimeouts",
			Handler:    _MatchingService_ExpireTimeouts_Handler,
		},
		{
			MethodName: "GetDeposit",
			Handler:    _MatchingService_GetDeposit_Handler,
		},
		{
			MethodName: "GetBasket",
			Handler:    _MatchingService_GetBasket_Handler,
		},
		{
			MethodName: "GetMatch",
			Handler:    _MatchingService_GetMatch_Handler,
		},
		{
			MethodName: "CheckHealth",
			Handler:    _MatchingService_CheckHealth_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _MatchingService_GetMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/matching/v1/matching.proto",
}
