// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsSuccess(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_SUCCESS.String() && e.Code == 500
}

func ErrorSuccess(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_SUCCESS.String(), fmt.Sprintf(format, args...))
}

func IsInvalidParams(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INVALID_PARAMS.String() && e.Code == 400
}

func ErrorInvalidParams(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_INVALID_PARAMS.String(), fmt.Sprintf(format, args...))
}

func IsDepositNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_DEPOSIT_NOT_FOUND.String() && e.Code == 404
}

func ErrorDepositNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_DEPOSIT_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsBasketNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_BASKET_NOT_FOUND.String() && e.Code == 404
}

func ErrorBasketNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_BASKET_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsMatchNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_MATCH_NOT_FOUND.String() && e.Code == 404
}

func ErrorMatchNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_MATCH_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsDepositAlreadyMatched(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_DEPOSIT_ALREADY_MATCHED.String() && e.Code == 409
}

func ErrorDepositAlreadyMatched(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_DEPOSIT_ALREADY_MATCHED.String(), fmt.Sprintf(format, args...))
}

func IsBasketClosed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_BASKET_CLOSED.String() && e.Code == 409
}

func ErrorBasketClosed(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_BASKET_CLOSED.String(), fmt.Sprintf(format, args...))
}

func IsShardLockBusy(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_SHARD_LOCK_BUSY.String() && e.Code == 429
}

func ErrorShardLockBusy(format string, args ...interface{}) *errors.Error {
	return errors.New(429, ErrorReason_SHARD_LOCK_BUSY.String(), fmt.Sprintf(format, args...))
}

func IsInternalError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INTERNAL_ERROR.String() && e.Code == 500
}

func ErrorInternalError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_INTERNAL_ERROR.String(), fmt.Sprintf(format, args...))
}
