// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: pkg/api/matching/v1/error_reason.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorReason 是撮合服务业务错误码。
type ErrorReason int32

const (
	ErrorReason_SUCCESS                 ErrorReason = 0
	ErrorReason_INVALID_PARAMS          ErrorReason = 400001
	ErrorReason_DEPOSIT_NOT_FOUND       ErrorReason = 400002
	ErrorReason_BASKET_NOT_FOUND        ErrorReason = 400003
	ErrorReason_MATCH_NOT_FOUND         ErrorReason = 400004
	ErrorReason_DEPOSIT_ALREADY_MATCHED ErrorReason = 400005
	ErrorReason_BASKET_CLOSED           ErrorReason = 400006
	ErrorReason_SHARD_LOCK_BUSY         ErrorReason = 400007
	ErrorReason_INTERNAL_ERROR          ErrorReason = 500001
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0:      "SUCCESS",
		400001: "INVALID_PARAMS",
		400002: "DEPOSIT_NOT_FOUND",
		400003: "BASKET_NOT_FOUND",
		400004: "MATCH_NOT_FOUND",
		400005: "DEPOSIT_ALREADY_MATCHED",
		400006: "BASKET_CLOSED",
		400007: "SHARD_LOCK_BUSY",
		500001: "INTERNAL_ERROR",
	}
	ErrorReason_value = map[string]int32{
		"SUCCESS":                 0,
		"INVALID_PARAMS":          400001,
		"DEPOSIT_NOT_FOUND":       400002,
		"BASKET_NOT_FOUND":        400003,
		"MATCH_NOT_FOUND":         400004,
		"DEPOSIT_ALREADY_MATCHED": 400005,
		"BASKET_CLOSED":           400006,
		"SHARD_LOCK_BUSY":         400007,
		"INTERNAL_ERROR":          500001,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_matching_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_pkg_api_matching_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_matching_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_pkg_api_matching_v1_error_reason_proto protoreflect.FileDescriptor

const file_pkg_api_matching_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"&pkg/api/matching/v1/error_reason.proto\x12\vmatching.v1\x1a\x13errors/errors.proto*\x8f\x02\n" +
	"\vErrorReason\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\x1a\n" +
	"\x0eINVALID_PARAMS\x10\x81\xb5\x18\x1a\x04\xa8E\x90\x03\x12\x1d\n" +
	"\x11DEPOSIT_NOT_FOUND\x10\x82\xb5\x18\x1a\x04\xa8E\x94\x03\x12\x1c\n" +
	"\x10BASKET_NOT_FOUND\x10\x83\xb5\x18\x1a\x04\xa8E\x94\x03\x12\x1b\n" +
	"\x0fMATCH_NOT_FOUND\x10\x84\xb5\x18\x1a\x04\xa8E\x94\x03\x12#\n" +
	"\x17DEPOSIT_ALREADY_MATCHED\x10\x85\xb5\x18\x1a\x04\xa8E\x99\x03\x12\x19\n" +
	"\rBASKET_CLOSED\x10\x86\xb5\x18\x1a\x04\xa8E\x99\x03\x12\x1b\n" +
	"\x0fSHARD_LOCK_BUSY\x10\x87\xb5\x18\x1a\x04\xa8E\xad\x03\x12\x1a\n" +
	"\x0eINTERNAL_ERROR\x10\xa1\xc2\x1e\x1a\x04\xa8E\xf4\x03\x1a\x04\xa0E\xf4\x03B)Z'matching-service/pkg/api/matching/v1;v1b\x06proto3"

var (
	file_pkg_api_matching_v1_error_reason_proto_rawDescOnce sync.Once
	file_pkg_api_matching_v1_error_reason_proto_rawDescData []byte
)

func file_pkg_api_matching_v1_error_reason_proto_rawDescGZIP() []byte {
	file_pkg_api_matching_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_pkg_api_matching_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_matching_v1_error_reason_proto_rawDesc), len(file_pkg_api_matching_v1_error_reason_proto_rawDesc)))
	})
	return file_pkg_api_matching_v1_error_reason_proto_rawDescData
}

var file_pkg_api_matching_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_api_matching_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: matching.v1.ErrorReason
}
var file_pkg_api_matching_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_api_matching_v1_error_reason_proto_init() }
func file_pkg_api_matching_v1_error_reason_proto_init() {
	if File_pkg_api_matching_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_matching_v1_error_reason_proto_rawDesc), len(file_pkg_api_matching_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_api_matching_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_pkg_api_matching_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_pkg_api_matching_v1_error_reason_proto_enumTypes,
	}.Build()
	File_pkg_api_matching_v1_error_reason_proto = out.File
	file_pkg_api_matching_v1_error_reason_proto_goTypes = nil
	file_pkg_api_matching_v1_error_reason_proto_depIdxs = nil
}
