// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: pkg/api/matching/v1/matching.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateBasketRequest 是创建出金撮合篮子的请求。
type CreateBasketRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// basket_no 是撮合篮子编号。
	BasketNo string `protobuf:"bytes,1,opt,name=basket_no,json=basketNo,proto3" json:"basket_no,omitempty"`
	// withdraw_no 是出金单号。
	WithdrawNo string `protobuf:"bytes,2,opt,name=withdraw_no,json=withdrawNo,proto3" json:"withdraw_no,omitempty"`
	// channel 是支付渠道。
	Channel string `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	// currency 是币种。
	Currency string `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	// target_amount 是出金目标金额，使用最小货币单位。
	TargetAmount int64 `protobuf:"varint,5,opt,name=target_amount,json=targetAmount,proto3" json:"target_amount,omitempty"`
	// expire_at 是篮子过期时间。
	ExpireAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBasketRequest) Reset() {
	*x = CreateBasketRequest{}
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBasketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBasketRequest) ProtoMessage() {}

func (x *CreateBasketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBasketRequest.ProtoReflect.Descriptor instead.
func (*CreateBasketRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_matching_v1_matching_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBasketRequest) GetBasketNo() string {
	if x != nil {
		return x.BasketNo
	}
	return ""
}

func (x *CreateBasketRequest) GetWithdrawNo() string {
	if x != nil {
		return x.WithdrawNo
	}
	return ""
}

func (x *CreateBasketRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *CreateBasketRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateBasketRequest) GetTargetAmount() int64 {
	if x != nil {
		return x.TargetAmount
	}
	return 0
}

func (x *CreateBasketRequest) GetExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireAt
	}
	return nil
}

// CreateBasketReply 是创建出金撮合篮子的响应。
type CreateBasketReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// basket_no 是撮合篮子编号。
	BasketNo      string `protobuf:"bytes,1,opt,name=basket_no,json=basketNo,proto3" json:"basket_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBasketReply) Reset() {
	*x = CreateBasketReply{}
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBasketReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBasketReply) ProtoMessage() {}

func (x *CreateBasketReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBasketReply.ProtoReflect.Descriptor instead.
func (*CreateBasketReply) Descriptor() ([]byte, []int) {
	return file_pkg_api_matching_v1_matching_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBasketReply) GetBasketNo() string {
	if x != nil {
		return x.BasketNo
	}
	return ""
}

// SubmitDepositRequest 是提交入金单的请求。
type SubmitDepositRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// deposit_no 是入金单号。
	DepositNo string `protobuf:"bytes,1,opt,name=deposit_no,json=depositNo,proto3" json:"deposit_no,omitempty"`
	// channel 是支付渠道。
	Channel string `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	// currency 是币种。
	Currency string `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	// amount 是入金金额，使用最小货币单位。
	Amount int64 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	// expire_at 是入金单过期时间。
	ExpireAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitDepositRequest) Reset() {
	*x = SubmitDepositRequest{}
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitDepositRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitDepositRequest) ProtoMessage() {}

func (x *SubmitDepositRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitDepositRequest.ProtoReflect.Descriptor instead.
func (*SubmitDepositRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_matching_v1_matching_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitDepositRequest) GetDepositNo() string {
	if x != nil {
		return x.DepositNo
	}
	return ""
}

func (x *SubmitDepositRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *SubmitDepositRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *SubmitDepositRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SubmitDepositRequest) GetExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireAt
	}
	return nil
}

// SubmitDepositReply 是提交入金单的响应。
type SubmitDepositReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// result 是本次入金撮合结果。
	Result        *MatchResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitDepositReply) Reset() {
	*x = SubmitDepositReply{}
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitDepositReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitDepositReply) ProtoMessage() {}

func (x *SubmitDepositReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitDepositReply.ProtoReflect.Descriptor instead.
func (*SubmitDepositReply) Descriptor() ([]byte, []int) {
	return file_pkg_api_matching_v1_matching_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitDepositReply) GetResult() *MatchResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// ExpireTimeoutsRequest 是处理超时数据的请求。
type ExpireTimeoutsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// now_unix 是当前 Unix 秒级时间戳。
	NowUnix int64 `protobuf:"varint,1,opt,name=now_unix,json=nowUnix,proto3" json:"now_unix,omitempty"`
	// limit 是本次最多处理数量。
	Limit         int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpireTimeoutsRequest) Reset() {
	*x = ExpireTimeoutsRequest{}
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpireTimeoutsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpireTimeoutsRequest) ProtoMessage() {}

func (x *ExpireTimeoutsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpireTimeoutsRequest.ProtoReflect.Descriptor instead.
func (*ExpireTimeoutsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_matching_v1_matching_proto_rawDescGZIP(), []int{4}
}

func (x *ExpireTimeoutsRequest) GetNowUnix() int64 {
	if x != nil {
		return x.NowUnix
	}
	return 0
}

func (x *ExpireTimeoutsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ExpireTimeoutsReply 是处理超时数据的响应。
type ExpireTimeoutsReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// waiting_deposits 是已处理的等待中入金单数量。
	WaitingDeposits int32 `protobuf:"varint,1,opt,name=waiting_deposits,json=waitingDeposits,proto3" json:"waiting_deposits,omitempty"`
	// locked_deposits 是已处理的锁定中入金单数量。
	LockedDeposits int32 `protobuf:"varint,2,opt,name=locked_deposits,json=lockedDeposits,proto3" json:"locked_deposits,omitempty"`
	// baskets 是已处理的出金篮子数量。
	Baskets       int32 `protobuf:"varint,3,opt,name=baskets,proto3" json:"baskets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpireTimeoutsReply) Reset() {
	*x = ExpireTimeoutsReply{}
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpireTimeoutsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpireTimeoutsReply) ProtoMessage() {}

func (x *ExpireTimeoutsReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpireTimeoutsReply.ProtoReflect.Descriptor instead.
func (*ExpireTimeoutsReply) Descriptor() ([]byte, []int) {
	return file_pkg_api_matching_v1_matching_proto_rawDescGZIP(), []int{5}
}

func (x *ExpireTimeoutsReply) GetWaitingDeposits() int32 {
	if x != nil {
		return x.WaitingDeposits
	}
	return 0
}

func (x *ExpireTimeoutsReply) GetLockedDeposits() int32 {
	if x != nil {
		return x.LockedDeposits
	}
	return 0
}

func (x *ExpireTimeoutsReply) GetBaskets() int32 {
	if x != nil {
		return x.Baskets
	}
	return 0
}

// GetDepositRequest 是查询入金单的请求。
type GetDepositRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// deposit_no 是入金单号。
	DepositNo     string `protobuf:"bytes,1,opt,name=deposit_no,json=depositNo,proto3" json:"deposit_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepositRequest) Reset() {
	*x = GetDepositRequest{}
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepositRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepositRequest) ProtoMessage() {}

func (x *GetDepositRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepositRequest.ProtoReflect.Descriptor instead.
func (*GetDepositRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_matching_v1_matching_proto_rawDescGZIP(), []int{6}
}

func (x *GetDepositRequest) GetDepositNo() string {
	if x != nil {
		return x.DepositNo
	}
	return ""
}

// GetDepositReply 是查询入金单的响应。
type GetDepositReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// deposit 是入金单数据。
	Deposit       *DepositOrder `protobuf:"bytes,1,opt,name=deposit,proto3" json:"deposit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepositReply) Reset() {
	*x = GetDepositReply{}
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepositReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepositReply) ProtoMessage() {}

func (x *GetDepositReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepositReply.ProtoReflect.Descriptor instead.
func (*GetDepositReply) Descriptor() ([]byte, []int) {
	return file_pkg_api_matching_v1_matching_proto_rawDescGZIP(), []int{7}
}

func (x *GetDepositReply) GetDeposit() *DepositOrder {
	if x != nil {
		return x.Deposit
	}
	return nil
}

// GetBasketRequest 是查询出金篮子的请求。
type GetBasketRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// basket_no 是撮合篮子编号。
	BasketNo      string `protobuf:"bytes,1,opt,name=basket_no,json=basketNo,proto3" json:"basket_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBasketRequest) Reset() {
	*x = GetBasketRequest{}
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBasketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBasketRequest) ProtoMessage() {}

func (x *GetBasketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBasketRequest.ProtoReflect.Descriptor instead.
func (*GetBasketRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_matching_v1_matching_proto_rawDescGZIP(), []int{8}
}

func (x *GetBasketRequest) GetBasketNo() string {
	if x != nil {
		return x.BasketNo
	}
	return ""
}

// GetBasketReply 是查询出金篮子的响应。
type GetBasketReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// basket 是出金撮合篮子数据。
	Basket        *WithdrawBasket `protobuf:"bytes,1,opt,name=basket,proto3" json:"basket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBasketReply) Reset() {
	*x = GetBasketReply{}
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBasketReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBasketReply) ProtoMessage() {}

func (x *GetBasketReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBasketReply.ProtoReflect.Descriptor instead.
func (*GetBasketReply) Descriptor() ([]byte, []int) {
	return file_pkg_api_matching_v1_matching_proto_rawDescGZIP(), []int{9}
}

func (x *GetBasketReply) GetBasket() *WithdrawBasket {
	if x != nil {
		return x.Basket
	}
	return nil
}

// GetMatchRequest 是查询撮合记录的请求。
type GetMatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// match_no 是撮合记录编号。
	MatchNo string `protobuf:"bytes,1,opt,name=match_no,json=matchNo,proto3" json:"match_no,omitempty"`
	// basket_no 是撮合篮子编号。
	BasketNo string `protobuf:"bytes,2,opt,name=basket_no,json=basketNo,proto3" json:"basket_no,omitempty"`
	// withdraw_no 是出金单号。
	WithdrawNo    string `protobuf:"bytes,3,opt,name=withdraw_no,json=withdrawNo,proto3" json:"withdraw_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMatchRequest) Reset() {
	*x = GetMatchRequest{}
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchRequest) ProtoMessage() {}

func (x *GetMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchRequest.ProtoReflect.Descriptor instead.
func (*GetMatchRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_matching_v1_matching_proto_rawDescGZIP(), []int{10}
}

func (x *GetMatchRequest) GetMatchNo() string {
	if x != nil {
		return x.MatchNo
	}
	return ""
}

func (x *GetMatchRequest) GetBasketNo() string {
	if x != nil {
		return x.BasketNo
	}
	return ""
}

func (x *GetMatchRequest) GetWithdrawNo() string {
	if x != nil {
		return x.WithdrawNo
	}
	return ""
}

// GetMatchReply 是查询撮合记录的响应。
type GetMatchReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// match 是撮合主记录。
	Match *MatchRecord `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"`
	// deposits 是参与撮合的入金明细。
	Deposits      []*MatchRecordDeposit `protobuf:"bytes,2,rep,name=deposits,proto3" json:"deposits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMatchReply) Reset() {
	*x = GetMatchReply{}
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchReply) ProtoMessage() {}

func (x *GetMatchReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchReply.ProtoReflect.Descriptor instead.
func (*GetMatchReply) Descriptor() ([]byte, []int) {
	return file_pkg_api_matching_v1_matching_proto_rawDescGZIP(), []int{11}
}

func (x *GetMatchReply) GetMatch() *MatchRecord {
	if x != nil {
		return x.Match
	}
	return nil
}

func (x *GetMatchReply) GetDeposits() []*MatchRecordDeposit {
	if x != nil {
		return x.Deposits
	}
	return nil
}

// CheckHealthRequest 是健康检查请求。
type CheckHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckHealthRequest) Reset() {
	*x = CheckHealthRequest{}
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHealthRequest) ProtoMessage() {}

func (x *CheckHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHealthRequest.ProtoReflect.Descriptor instead.
func (*CheckHealthRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_matching_v1_matching_proto_rawDescGZIP(), []int{12}
}

// CheckHealthReply 是健康检查响应。
type CheckHealthReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ok 表示整体是否健康。
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// components 是各依赖组件的健康状态。
	Components    []*HealthComponent `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckHealthReply) Reset() {
	*x = CheckHealthReply{}
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckHealthReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHealthReply) ProtoMessage() {}

func (x *CheckHealthReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHealthReply.ProtoReflect.Descriptor instead.
func (*CheckHealthReply) Descriptor() ([]byte, []int) {
	return file_pkg_api_matching_v1_matching_proto_rawDescGZIP(), []int{13}
}

func (x *CheckHealthReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CheckHealthReply) GetComponents() []*HealthComponent {
	if x != nil {
		return x.Components
	}
	return nil
}

// HealthComponent 是单个依赖组件的健康状态。
type HealthComponent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name 是组件名称。
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// ok 表示组件是否健康。
	Ok bool `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	// message 是组件健康说明。
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthComponent) Reset() {
	*x = HealthComponent{}
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthComponent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthComponent) ProtoMessage() {}

func (x *HealthComponent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthComponent.ProtoReflect.Descriptor instead.
func (*HealthComponent) Descriptor() ([]byte, []int) {
	return file_pkg_api_matching_v1_matching_proto_rawDescGZIP(), []int{14}
}

func (x *HealthComponent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HealthComponent) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthComponent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// MatchResult 是一次撮合尝试的结果。
type MatchResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// matched 表示是否已完成撮合。
	Matched bool `protobuf:"varint,1,opt,name=matched,proto3" json:"matched,omitempty"`
	// attached 表示入金单是否已挂入篮子。
	Attached bool `protobuf:"varint,2,opt,name=attached,proto3" json:"attached,omitempty"`
	// basket_no 是撮合篮子编号。
	BasketNo string `protobuf:"bytes,3,opt,name=basket_no,json=basketNo,proto3" json:"basket_no,omitempty"`
	// withdraw_no 是出金单号。
	WithdrawNo string `protobuf:"bytes,4,opt,name=withdraw_no,json=withdrawNo,proto3" json:"withdraw_no,omitempty"`
	// channel 是支付渠道。
	Channel string `protobuf:"bytes,5,opt,name=channel,proto3" json:"channel,omitempty"`
	// currency 是币种。
	Currency string `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	// deposit_nos 是参与撮合的入金单号列表。
	DepositNos []string `protobuf:"bytes,7,rep,name=deposit_nos,json=depositNos,proto3" json:"deposit_nos,omitempty"`
	// target_amount 是出金目标金额，使用最小货币单位。
	TargetAmount int64 `protobuf:"varint,8,opt,name=target_amount,json=targetAmount,proto3" json:"target_amount,omitempty"`
	// matched_amount 是已撮合金额，使用最小货币单位。
	MatchedAmount int64 `protobuf:"varint,9,opt,name=matched_amount,json=matchedAmount,proto3" json:"matched_amount,omitempty"`
	// short_amount 是少发金额，使用最小货币单位。
	ShortAmount int64 `protobuf:"varint,10,opt,name=short_amount,json=shortAmount,proto3" json:"short_amount,omitempty"`
	// pending 表示撮合是否仍在等待更多入金。
	Pending bool `protobuf:"varint,11,opt,name=pending,proto3" json:"pending,omitempty"`
	// failed_reason 是撮合失败原因。
	FailedReason  string `protobuf:"bytes,12,opt,name=failed_reason,json=failedReason,proto3" json:"failed_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchResult) Reset() {
	*x = MatchResult{}
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchResult) ProtoMessage() {}

func (x *MatchResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchResult.ProtoReflect.Descriptor instead.
func (*MatchResult) Descriptor() ([]byte, []int) {
	return file_pkg_api_matching_v1_matching_proto_rawDescGZIP(), []int{15}
}

func (x *MatchResult) GetMatched() bool {
	if x != nil {
		return x.Matched
	}
	return false
}

func (x *MatchResult) GetAttached() bool {
	if x != nil {
		return x.Attached
	}
	return false
}

func (x *MatchResult) GetBasketNo() string {
	if x != nil {
		return x.BasketNo
	}
	return ""
}

func (x *MatchResult) GetWithdrawNo() string {
	if x != nil {
		return x.WithdrawNo
	}
	return ""
}

func (x *MatchResult) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *MatchResult) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *MatchResult) GetDepositNos() []string {
	if x != nil {
		return x.DepositNos
	}
	return nil
}

func (x *MatchResult) GetTargetAmount() int64 {
	if x != nil {
		return x.TargetAmount
	}
	return 0
}

func (x *MatchResult) GetMatchedAmount() int64 {
	if x != nil {
		return x.MatchedAmount
	}
	return 0
}

func (x *MatchResult) GetShortAmount() int64 {
	if x != nil {
		return x.ShortAmount
	}
	return 0
}

func (x *MatchResult) GetPending() bool {
	if x != nil {
		return x.Pending
	}
	return false
}

func (x *MatchResult) GetFailedReason() string {
	if x != nil {
		return x.FailedReason
	}
	return ""
}

// DepositOrder 是入金单数据。
type DepositOrder struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// deposit_no 是入金单号。
	DepositNo string `protobuf:"bytes,1,opt,name=deposit_no,json=depositNo,proto3" json:"deposit_no,omitempty"`
	// merchant_id 是商户编号。
	MerchantId int64 `protobuf:"varint,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	// channel 是支付渠道。
	Channel string `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	// currency 是币种。
	Currency string `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	// amount 是入金金额，使用最小货币单位。
	Amount int64 `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	// status 是入金单状态。
	Status int32 `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	// expire_at 是入金单过期时间。
	ExpireAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	// matched_basket_no 是已匹配的撮合篮子编号。
	MatchedBasketNo string `protobuf:"bytes,8,opt,name=matched_basket_no,json=matchedBasketNo,proto3" json:"matched_basket_no,omitempty"`
	// match_no 是撮合记录编号。
	MatchNo string `protobuf:"bytes,9,opt,name=match_no,json=matchNo,proto3" json:"match_no,omitempty"`
	// created_at 是创建时间。
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// updated_at 是更新时间。
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositOrder) Reset() {
	*x = DepositOrder{}
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositOrder) ProtoMessage() {}

func (x *DepositOrder) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositOrder.ProtoReflect.Descriptor instead.
func (*DepositOrder) Descriptor() ([]byte, []int) {
	return file_pkg_api_matching_v1_matching_proto_rawDescGZIP(), []int{16}
}

func (x *DepositOrder) GetDepositNo() string {
	if x != nil {
		return x.DepositNo
	}
	return ""
}

func (x *DepositOrder) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *DepositOrder) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *DepositOrder) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *DepositOrder) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DepositOrder) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DepositOrder) GetExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireAt
	}
	return nil
}

func (x *DepositOrder) GetMatchedBasketNo() string {
	if x != nil {
		return x.MatchedBasketNo
	}
	return ""
}

func (x *DepositOrder) GetMatchNo() string {
	if x != nil {
		return x.MatchNo
	}
	return ""
}

func (x *DepositOrder) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DepositOrder) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// WithdrawBasket 是出金撮合篮子数据。
type WithdrawBasket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// basket_no 是撮合篮子编号。
	BasketNo string `protobuf:"bytes,1,opt,name=basket_no,json=basketNo,proto3" json:"basket_no,omitempty"`
	// withdraw_no 是出金单号。
	WithdrawNo string `protobuf:"bytes,2,opt,name=withdraw_no,json=withdrawNo,proto3" json:"withdraw_no,omitempty"`
	// merchant_id 是商户编号。
	MerchantId int64 `protobuf:"varint,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	// channel 是支付渠道。
	Channel string `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`
	// currency 是币种。
	Currency string `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	// target_amount 是出金目标金额，使用最小货币单位。
	TargetAmount int64 `protobuf:"varint,6,opt,name=target_amount,json=targetAmount,proto3" json:"target_amount,omitempty"`
	// current_amount 是篮子当前已凑金额，使用最小货币单位。
	CurrentAmount int64 `protobuf:"varint,7,opt,name=current_amount,json=currentAmount,proto3" json:"current_amount,omitempty"`
	// status 是篮子状态。
	Status int32 `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	// expire_at 是篮子过期时间。
	ExpireAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	// version 是乐观锁版本号。
	Version int64 `protobuf:"varint,10,opt,name=version,proto3" json:"version,omitempty"`
	// created_at 是创建时间。
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// updated_at 是更新时间。
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawBasket) Reset() {
	*x = WithdrawBasket{}
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawBasket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawBasket) ProtoMessage() {}

func (x *WithdrawBasket) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawBasket.ProtoReflect.Descriptor instead.
func (*WithdrawBasket) Descriptor() ([]byte, []int) {
	return file_pkg_api_matching_v1_matching_proto_rawDescGZIP(), []int{17}
}

func (x *WithdrawBasket) GetBasketNo() string {
	if x != nil {
		return x.BasketNo
	}
	return ""
}

func (x *WithdrawBasket) GetWithdrawNo() string {
	if x != nil {
		return x.WithdrawNo
	}
	return ""
}

func (x *WithdrawBasket) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *WithdrawBasket) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *WithdrawBasket) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *WithdrawBasket) GetTargetAmount() int64 {
	if x != nil {
		return x.TargetAmount
	}
	return 0
}

func (x *WithdrawBasket) GetCurrentAmount() int64 {
	if x != nil {
		return x.CurrentAmount
	}
	return 0
}

func (x *WithdrawBasket) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *WithdrawBasket) GetExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireAt
	}
	return nil
}

func (x *WithdrawBasket) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *WithdrawBasket) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *WithdrawBasket) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// MatchRecord 是撮合主记录。
type MatchRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// match_no 是撮合记录编号。
	MatchNo string `protobuf:"bytes,1,opt,name=match_no,json=matchNo,proto3" json:"match_no,omitempty"`
	// basket_no 是撮合篮子编号。
	BasketNo string `protobuf:"bytes,2,opt,name=basket_no,json=basketNo,proto3" json:"basket_no,omitempty"`
	// withdraw_no 是出金单号。
	WithdrawNo string `protobuf:"bytes,3,opt,name=withdraw_no,json=withdrawNo,proto3" json:"withdraw_no,omitempty"`
	// target_amount 是出金目标金额，使用最小货币单位。
	TargetAmount int64 `protobuf:"varint,4,opt,name=target_amount,json=targetAmount,proto3" json:"target_amount,omitempty"`
	// matched_amount 是实际撮合金额，使用最小货币单位。
	MatchedAmount int64 `protobuf:"varint,5,opt,name=matched_amount,json=matchedAmount,proto3" json:"matched_amount,omitempty"`
	// short_amount 是少发金额，使用最小货币单位。
	ShortAmount int64 `protobuf:"varint,6,opt,name=short_amount,json=shortAmount,proto3" json:"short_amount,omitempty"`
	// channel 是支付渠道。
	Channel string `protobuf:"bytes,7,opt,name=channel,proto3" json:"channel,omitempty"`
	// currency 是币种。
	Currency string `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`
	// status 是撮合记录状态。
	Status int32 `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	// created_at 是创建时间。
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// updated_at 是更新时间。
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchRecord) Reset() {
	*x = MatchRecord{}
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchRecord) ProtoMessage() {}

func (x *MatchRecord) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchRecord.ProtoReflect.Descriptor instead.
func (*MatchRecord) Descriptor() ([]byte, []int) {
	return file_pkg_api_matching_v1_matching_proto_rawDescGZIP(), []int{18}
}

func (x *MatchRecord) GetMatchNo() string {
	if x != nil {
		return x.MatchNo
	}
	return ""
}

func (x *MatchRecord) GetBasketNo() string {
	if x != nil {
		return x.BasketNo
	}
	return ""
}

func (x *MatchRecord) GetWithdrawNo() string {
	if x != nil {
		return x.WithdrawNo
	}
	return ""
}

func (x *MatchRecord) GetTargetAmount() int64 {
	if x != nil {
		return x.TargetAmount
	}
	return 0
}

func (x *MatchRecord) GetMatchedAmount() int64 {
	if x != nil {
		return x.MatchedAmount
	}
	return 0
}

func (x *MatchRecord) GetShortAmount() int64 {
	if x != nil {
		return x.ShortAmount
	}
	return 0
}

func (x *MatchRecord) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *MatchRecord) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *MatchRecord) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MatchRecord) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MatchRecord) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// DepositEventMessage 是入金 RocketMQ 消息信封。
type DepositEventMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// event_id 是幂等事件 ID。
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// topic 是 RocketMQ 主题。
	Topic string `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	// data 是入金单数据。
	Data          *DepositOrder `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositEventMessage) Reset() {
	*x = DepositEventMessage{}
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositEventMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositEventMessage) ProtoMessage() {}

func (x *DepositEventMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositEventMessage.ProtoReflect.Descriptor instead.
func (*DepositEventMessage) Descriptor() ([]byte, []int) {
	return file_pkg_api_matching_v1_matching_proto_rawDescGZIP(), []int{19}
}

func (x *DepositEventMessage) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *DepositEventMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *DepositEventMessage) GetData() *DepositOrder {
	if x != nil {
		return x.Data
	}
	return nil
}

// WithdrawEventMessage 是出金 RocketMQ 消息信封。
type WithdrawEventMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// event_id 是幂等事件 ID。
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// topic 是 RocketMQ 主题。
	Topic string `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	// data 是出金篮子数据。
	Data          *WithdrawBasket `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawEventMessage) Reset() {
	*x = WithdrawEventMessage{}
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawEventMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawEventMessage) ProtoMessage() {}

func (x *WithdrawEventMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawEventMessage.ProtoReflect.Descriptor instead.
func (*WithdrawEventMessage) Descriptor() ([]byte, []int) {
	return file_pkg_api_matching_v1_matching_proto_rawDescGZIP(), []int{20}
}

func (x *WithdrawEventMessage) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *WithdrawEventMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *WithdrawEventMessage) GetData() *WithdrawBasket {
	if x != nil {
		return x.Data
	}
	return nil
}

// MatchRecordDeposit 是撮合记录里的入金明细。
type MatchRecordDeposit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// match_no 是撮合记录编号。
	MatchNo string `protobuf:"bytes,1,opt,name=match_no,json=matchNo,proto3" json:"match_no,omitempty"`
	// withdraw_no 是出金单号。
	WithdrawNo string `protobuf:"bytes,2,opt,name=withdraw_no,json=withdrawNo,proto3" json:"withdraw_no,omitempty"`
	// deposit_no 是入金单号。
	DepositNo string `protobuf:"bytes,3,opt,name=deposit_no,json=depositNo,proto3" json:"deposit_no,omitempty"`
	// amount 是入金金额，使用最小货币单位。
	Amount int64 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	// created_at 是创建时间。
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchRecordDeposit) Reset() {
	*x = MatchRecordDeposit{}
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchRecordDeposit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchRecordDeposit) ProtoMessage() {}

func (x *MatchRecordDeposit) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_matching_v1_matching_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchRecordDeposit.ProtoReflect.Descriptor instead.
func (*MatchRecordDeposit) Descriptor() ([]byte, []int) {
	return file_pkg_api_matching_v1_matching_proto_rawDescGZIP(), []int{21}
}

func (x *MatchRecordDeposit) GetMatchNo() string {
	if x != nil {
		return x.MatchNo
	}
	return ""
}

func (x *MatchRecordDeposit) GetWithdrawNo() string {
	if x != nil {
		return x.WithdrawNo
	}
	return ""
}

func (x *MatchRecordDeposit) GetDepositNo() string {
	if x != nil {
		return x.DepositNo
	}
	return ""
}

func (x *MatchRecordDeposit) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *MatchRecordDeposit) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_pkg_api_matching_v1_matching_proto protoreflect.FileDescriptor

const file_pkg_api_matching_v1_matching_proto_rawDesc = "" +
	"\n" +
	"\"pkg/api/matching/v1/matching.proto\x12\vmatching.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\"\x9a\x02\n" +
	"\x13CreateBasketRequest\x12$\n" +
	"\tbasket_no\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\bbasketNo\x12(\n" +
	"\vwithdraw_no\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\n" +
	"withdrawNo\x12!\n" +
	"\achannel\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\achannel\x12#\n" +
	"\bcurrency\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\bcurrency\x12,\n" +
	"\rtarget_amount\x18\x05 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\ftargetAmount\x127\n" +
	"\texpire_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bexpireAtJ\x04\b\x06\x10\a\"0\n" +
	"\x11CreateBasketReply\x12\x1b\n" +
	"\tbasket_no\x18\x01 \x01(\tR\bbasketNo\"\xe0\x01\n" +
	"\x14SubmitDepositRequest\x12&\n" +
	"\n" +
	"deposit_no\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tdepositNo\x12!\n" +
	"\achannel\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\achannel\x12#\n" +
	"\bcurrency\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\bcurrency\x12\x1f\n" +
	"\x06amount\x18\x04 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06amount\x127\n" +
	"\texpire_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bexpireAt\"F\n" +
	"\x12SubmitDepositReply\x120\n" +
	"\x06result\x18\x01 \x01(\v2\x18.matching.v1.MatchResultR\x06result\"H\n" +
	"\x15ExpireTimeoutsRequest\x12\x19\n" +
	"\bnow_unix\x18\x01 \x01(\x03R\anowUnix\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x83\x01\n" +
	"\x13ExpireTimeoutsReply\x12)\n" +
	"\x10waiting_deposits\x18\x01 \x01(\x05R\x0fwaitingDeposits\x12'\n" +
	"\x0flocked_deposits\x18\x02 \x01(\x05R\x0elockedDeposits\x12\x18\n" +
	"\abaskets\x18\x03 \x01(\x05R\abaskets\";\n" +
	"\x11GetDepositRequest\x12&\n" +
	"\n" +
	"deposit_no\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tdepositNo\"F\n" +
	"\x0fGetDepositReply\x123\n" +
	"\adeposit\x18\x01 \x01(\v2\x19.matching.v1.DepositOrderR\adeposit\"8\n" +
	"\x10GetBasketRequest\x12$\n" +
	"\tbasket_no\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\bbasketNo\"E\n" +
	"\x0eGetBasketReply\x123\n" +
	"\x06basket\x18\x01 \x01(\v2\x1b.matching.v1.WithdrawBasketR\x06basket\"j\n" +
	"\x0fGetMatchRequest\x12\x19\n" +
	"\bmatch_no\x18\x01 \x01(\tR\amatchNo\x12\x1b\n" +
	"\tbasket_no\x18\x02 \x01(\tR\bbasketNo\x12\x1f\n" +
	"\vwithdraw_no\x18\x03 \x01(\tR\n" +
	"withdrawNo\"|\n" +
	"\rGetMatchReply\x12.\n" +
	"\x05match\x18\x01 \x01(\v2\x18.matching.v1.MatchRecordR\x05match\x12;\n" +
	"\bdeposits\x18\x02 \x03(\v2\x1f.matching.v1.MatchRecordDepositR\bdeposits\"\x14\n" +
	"\x12CheckHealthRequest\"`\n" +
	"\x10CheckHealthReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12<\n" +
	"\n" +
	"components\x18\x02 \x03(\v2\x1c.matching.v1.HealthComponentR\n" +
	"components\"O\n" +
	"\x0fHealthComponent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x86\x03\n" +
	"\vMatchResult\x12\x18\n" +
	"\amatched\x18\x01 \x01(\bR\amatched\x12\x1a\n" +
	"\battached\x18\x02 \x01(\bR\battached\x12\x1b\n" +
	"\tbasket_no\x18\x03 \x01(\tR\bbasketNo\x12\x1f\n" +
	"\vwithdraw_no\x18\x04 \x01(\tR\n" +
	"withdrawNo\x12\x18\n" +
	"\achannel\x18\x05 \x01(\tR\achannel\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x1f\n" +
	"\vdeposit_nos\x18\a \x03(\tR\n" +
	"depositNos\x12#\n" +
	"\rtarget_amount\x18\b \x01(\x03R\ftargetAmount\x12%\n" +
	"\x0ematched_amount\x18\t \x01(\x03R\rmatchedAmount\x12!\n" +
	"\fshort_amount\x18\n" +
	" \x01(\x03R\vshortAmount\x12\x18\n" +
	"\apending\x18\v \x01(\bR\apending\x12#\n" +
	"\rfailed_reason\x18\f \x01(\tR\ffailedReason\"\xaa\x03\n" +
	"\fDepositOrder\x12\x1d\n" +
	"\n" +
	"deposit_no\x18\x01 \x01(\tR\tdepositNo\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\x03R\n" +
	"merchantId\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x127\n" +
	"\texpire_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bexpireAt\x12*\n" +
	"\x11matched_basket_no\x18\b \x01(\tR\x0fmatchedBasketNo\x12\x19\n" +
	"\bmatch_no\x18\t \x01(\tR\amatchNo\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xd2\x03\n" +
	"\x0eWithdrawBasket\x12\x1b\n" +
	"\tbasket_no\x18\x01 \x01(\tR\bbasketNo\x12\x1f\n" +
	"\vwithdraw_no\x18\x02 \x01(\tR\n" +
	"withdrawNo\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\x03R\n" +
	"merchantId\x12\x18\n" +
	"\achannel\x18\x04 \x01(\tR\achannel\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12#\n" +
	"\rtarget_amount\x18\x06 \x01(\x03R\ftargetAmount\x12%\n" +
	"\x0ecurrent_amount\x18\a \x01(\x03R\rcurrentAmount\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x127\n" +
	"\texpire_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\bexpireAt\x12\x18\n" +
	"\aversion\x18\n" +
	" \x01(\x03R\aversion\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x99\x03\n" +
	"\vMatchRecord\x12\x19\n" +
	"\bmatch_no\x18\x01 \x01(\tR\amatchNo\x12\x1b\n" +
	"\tbasket_no\x18\x02 \x01(\tR\bbasketNo\x12\x1f\n" +
	"\vwithdraw_no\x18\x03 \x01(\tR\n" +
	"withdrawNo\x12#\n" +
	"\rtarget_amount\x18\x04 \x01(\x03R\ftargetAmount\x12%\n" +
	"\x0ematched_amount\x18\x05 \x01(\x03R\rmatchedAmount\x12!\n" +
	"\fshort_amount\x18\x06 \x01(\x03R\vshortAmount\x12\x18\n" +
	"\achannel\x18\a \x01(\tR\achannel\x12\x1a\n" +
	"\bcurrency\x18\b \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"u\n" +
	"\x13DepositEventMessage\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12-\n" +
	"\x04data\x18\x03 \x01(\v2\x19.matching.v1.DepositOrderR\x04data\"x\n" +
	"\x14WithdrawEventMessage\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12/\n" +
	"\x04data\x18\x03 \x01(\v2\x1b.matching.v1.WithdrawBasketR\x04data\"\xc2\x01\n" +
	"\x12MatchRecordDeposit\x12\x19\n" +
	"\bmatch_no\x18\x01 \x01(\tR\amatchNo\x12\x1f\n" +
	"\vwithdraw_no\x18\x02 \x01(\tR\n" +
	"withdrawNo\x12\x1d\n" +
	"\n" +
	"deposit_no\x18\x03 \x01(\tR\tdepositNo\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2\xba\x04\n" +
	"\x0fMatchingService\x12P\n" +
	"\fCreateBasket\x12 .matching.v1.CreateBasketRequest\x1a\x1e.matching.v1.CreateBasketReply\x12S\n" +
	"\rSubmitDeposit\x12!.matching.v1.SubmitDepositRequest\x1a\x1f.matching.v1.SubmitDepositReply\x12V\n" +
	"\x0eExpireTimeouts\x12\".matching.v1.ExpireTimeoutsRequest\x1a .matching.v1.ExpireTimeoutsReply\x12J\n" +
	"\n" +
	"GetDeposit\x12\x1e.matching.v1.GetDepositRequest\x1a\x1c.matching.v1.GetDepositReply\x12G\n" +
	"\tGetBasket\x12\x1d.matching.v1.GetBasketRequest\x1a\x1b.matching.v1.GetBasketReply\x12D\n" +
	"\bGetMatch\x12\x1c.matching.v1.GetMatchRequest\x1a\x1a.matching.v1.GetMatchReply\x12M\n" +
	"\vCheckHealth\x12\x1f.matching.v1.CheckHealthRequest\x1a\x1d.matching.v1.CheckHealthReplyB)Z'matching-service/pkg/api/matching/v1;v1b\x06proto3"

var (
	file_pkg_api_matching_v1_matching_proto_rawDescOnce sync.Once
	file_pkg_api_matching_v1_matching_proto_rawDescData []byte
)

func file_pkg_api_matching_v1_matching_proto_rawDescGZIP() []byte {
	file_pkg_api_matching_v1_matching_proto_rawDescOnce.Do(func() {
		file_pkg_api_matching_v1_matching_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_matching_v1_matching_proto_rawDesc), len(file_pkg_api_matching_v1_matching_proto_rawDesc)))
	})
	return file_pkg_api_matching_v1_matching_proto_rawDescData
}

var file_pkg_api_matching_v1_matching_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_pkg_api_matching_v1_matching_proto_goTypes = []any{
	(*CreateBasketRequest)(nil),   // 0: matching.v1.CreateBasketRequest
	(*CreateBasketReply)(nil),     // 1: matching.v1.CreateBasketReply
	(*SubmitDepositRequest)(nil),  // 2: matching.v1.SubmitDepositRequest
	(*SubmitDepositReply)(nil),    // 3: matching.v1.SubmitDepositReply
	(*ExpireTimeoutsRequest)(nil), // 4: matching.v1.ExpireTimeoutsRequest
	(*ExpireTimeoutsReply)(nil),   // 5: matching.v1.ExpireTimeoutsReply
	(*GetDepositRequest)(nil),     // 6: matching.v1.GetDepositRequest
	(*GetDepositReply)(nil),       // 7: matching.v1.GetDepositReply
	(*GetBasketRequest)(nil),      // 8: matching.v1.GetBasketRequest
	(*GetBasketReply)(nil),        // 9: matching.v1.GetBasketReply
	(*GetMatchRequest)(nil),       // 10: matching.v1.GetMatchRequest
	(*GetMatchReply)(nil),         // 11: matching.v1.GetMatchReply
	(*CheckHealthRequest)(nil),    // 12: matching.v1.CheckHealthRequest
	(*CheckHealthReply)(nil),      // 13: matching.v1.CheckHealthReply
	(*HealthComponent)(nil),       // 14: matching.v1.HealthComponent
	(*MatchResult)(nil),           // 15: matching.v1.MatchResult
	(*DepositOrder)(nil),          // 16: matching.v1.DepositOrder
	(*WithdrawBasket)(nil),        // 17: matching.v1.WithdrawBasket
	(*MatchRecord)(nil),           // 18: matching.v1.MatchRecord
	(*DepositEventMessage)(nil),   // 19: matching.v1.DepositEventMessage
	(*WithdrawEventMessage)(nil),  // 20: matching.v1.WithdrawEventMessage
	(*MatchRecordDeposit)(nil),    // 21: matching.v1.MatchRecordDeposit
	(*timestamppb.Timestamp)(nil), // 22: google.protobuf.Timestamp
}
var file_pkg_api_matching_v1_matching_proto_depIdxs = []int32{
	22, // 0: matching.v1.CreateBasketRequest.expire_at:type_name -> google.protobuf.Timestamp
	22, // 1: matching.v1.SubmitDepositRequest.expire_at:type_name -> google.protobuf.Timestamp
	15, // 2: matching.v1.SubmitDepositReply.result:type_name -> matching.v1.MatchResult
	16, // 3: matching.v1.GetDepositReply.deposit:type_name -> matching.v1.DepositOrder
	17, // 4: matching.v1.GetBasketReply.basket:type_name -> matching.v1.WithdrawBasket
	18, // 5: matching.v1.GetMatchReply.match:type_name -> matching.v1.MatchRecord
	21, // 6: matching.v1.GetMatchReply.deposits:type_name -> matching.v1.MatchRecordDeposit
	14, // 7: matching.v1.CheckHealthReply.components:type_name -> matching.v1.HealthComponent
	22, // 8: matching.v1.DepositOrder.expire_at:type_name -> google.protobuf.Timestamp
	22, // 9: matching.v1.DepositOrder.created_at:type_name -> google.protobuf.Timestamp
	22, // 10: matching.v1.DepositOrder.updated_at:type_name -> google.protobuf.Timestamp
	22, // 11: matching.v1.WithdrawBasket.expire_at:type_name -> google.protobuf.Timestamp
	22, // 12: matching.v1.WithdrawBasket.created_at:type_name -> google.protobuf.Timestamp
	22, // 13: matching.v1.WithdrawBasket.updated_at:type_name -> google.protobuf.Timestamp
	22, // 14: matching.v1.MatchRecord.created_at:type_name -> google.protobuf.Timestamp
	22, // 15: matching.v1.MatchRecord.updated_at:type_name -> google.protobuf.Timestamp
	16, // 16: matching.v1.DepositEventMessage.data:type_name -> matching.v1.DepositOrder
	17, // 17: matching.v1.WithdrawEventMessage.data:type_name -> matching.v1.WithdrawBasket
	22, // 18: matching.v1.MatchRecordDeposit.created_at:type_name -> google.protobuf.Timestamp
	0,  // 19: matching.v1.MatchingService.CreateBasket:input_type -> matching.v1.CreateBasketRequest
	2,  // 20: matching.v1.MatchingService.SubmitDeposit:input_type -> matching.v1.SubmitDepositRequest
	4,  // 21: matching.v1.MatchingService.ExpireTimeouts:input_type -> matching.v1.ExpireTimeoutsRequest
	6,  // 22: matching.v1.MatchingService.GetDeposit:input_type -> matching.v1.GetDepositRequest
	8,  // 23: matching.v1.MatchingService.GetBasket:input_type -> matching.v1.GetBasketRequest
	10, // 24: matching.v1.MatchingService.GetMatch:input_type -> matching.v1.GetMatchRequest
	12, // 25: matching.v1.MatchingService.CheckHealth:input_type -> matching.v1.CheckHealthRequest
	1,  // 26: matching.v1.MatchingService.CreateBasket:output_type -> matching.v1.CreateBasketReply
	3,  // 27: matching.v1.MatchingService.SubmitDeposit:output_type -> matching.v1.SubmitDepositReply
	5,  // 28: matching.v1.MatchingService.ExpireTimeouts:output_type -> matching.v1.ExpireTimeoutsReply
	7,  // 29: matching.v1.MatchingService.GetDeposit:output_type -> matching.v1.GetDepositReply
	9,  // 30: matching.v1.MatchingService.GetBasket:output_type -> matching.v1.GetBasketReply
	11, // 31: matching.v1.MatchingService.GetMatch:output_type -> matching.v1.GetMatchReply
	13, // 32: matching.v1.MatchingService.CheckHealth:output_type -> matching.v1.CheckHealthReply
	26, // [26:33] is the sub-list for method output_type
	19, // [19:26] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_pkg_api_matching_v1_matching_proto_init() }
func file_pkg_api_matching_v1_matching_proto_init() {
	if File_pkg_api_matching_v1_matching_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_matching_v1_matching_proto_rawDesc), len(file_pkg_api_matching_v1_matching_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_matching_v1_matching_proto_goTypes,
		DependencyIndexes: file_pkg_api_matching_v1_matching_proto_depIdxs,
		MessageInfos:      file_pkg_api_matching_v1_matching_proto_msgTypes,
	}.Build()
	File_pkg_api_matching_v1_matching_proto = out.File
	file_pkg_api_matching_v1_matching_proto_goTypes = nil
	file_pkg_api_matching_v1_matching_proto_depIdxs = nil
}
