// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: pkg/api/matching/v1/matching.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CreateBasketRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateBasketRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateBasketRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateBasketRequestMultiError, or nil if none found.
func (m *CreateBasketRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateBasketRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetBasketNo()) < 1 {
		err := CreateBasketRequestValidationError{
			field:  "BasketNo",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetWithdrawNo()) < 1 {
		err := CreateBasketRequestValidationError{
			field:  "WithdrawNo",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetChannel()) < 1 {
		err := CreateBasketRequestValidationError{
			field:  "Channel",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetCurrency()) < 1 {
		err := CreateBasketRequestValidationError{
			field:  "Currency",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetTargetAmount() <= 0 {
		err := CreateBasketRequestValidationError{
			field:  "TargetAmount",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetExpireAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateBasketRequestValidationError{
					field:  "ExpireAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateBasketRequestValidationError{
					field:  "ExpireAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetExpireAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateBasketRequestValidationError{
				field:  "ExpireAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateBasketRequestMultiError(errors)
	}

	return nil
}

// CreateBasketRequestMultiError is an error wrapping multiple validation
// errors returned by CreateBasketRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateBasketRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateBasketRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateBasketRequestMultiError) AllErrors() []error { return m }

// CreateBasketRequestValidationError is the validation error returned by
// CreateBasketRequest.Validate if the designated constraints aren't met.
type CreateBasketRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateBasketRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateBasketRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateBasketRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateBasketRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateBasketRequestValidationError) ErrorName() string {
	return "CreateBasketRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateBasketRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateBasketRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateBasketRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateBasketRequestValidationError{}

// Validate checks the field values on CreateBasketReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreateBasketReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateBasketReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateBasketReplyMultiError, or nil if none found.
func (m *CreateBasketReply) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateBasketReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for BasketNo

	if len(errors) > 0 {
		return CreateBasketReplyMultiError(errors)
	}

	return nil
}

// CreateBasketReplyMultiError is an error wrapping multiple validation errors
// returned by CreateBasketReply.ValidateAll() if the designated constraints
// aren't met.
type CreateBasketReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateBasketReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateBasketReplyMultiError) AllErrors() []error { return m }

// CreateBasketReplyValidationError is the validation error returned by
// CreateBasketReply.Validate if the designated constraints aren't met.
type CreateBasketReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateBasketReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateBasketReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateBasketReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateBasketReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateBasketReplyValidationError) ErrorName() string {
	return "CreateBasketReplyValidationError"
}

// Error satisfies the builtin error interface
func (e CreateBasketReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateBasketReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateBasketReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateBasketReplyValidationError{}

// Validate checks the field values on SubmitDepositRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SubmitDepositRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SubmitDepositRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SubmitDepositRequestMultiError, or nil if none found.
func (m *SubmitDepositRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SubmitDepositRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetDepositNo()) < 1 {
		err := SubmitDepositRequestValidationError{
			field:  "DepositNo",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetChannel()) < 1 {
		err := SubmitDepositRequestValidationError{
			field:  "Channel",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetCurrency()) < 1 {
		err := SubmitDepositRequestValidationError{
			field:  "Currency",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetAmount() <= 0 {
		err := SubmitDepositRequestValidationError{
			field:  "Amount",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetExpireAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SubmitDepositRequestValidationError{
					field:  "ExpireAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SubmitDepositRequestValidationError{
					field:  "ExpireAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetExpireAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SubmitDepositRequestValidationError{
				field:  "ExpireAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SubmitDepositRequestMultiError(errors)
	}

	return nil
}

// SubmitDepositRequestMultiError is an error wrapping multiple validation
// errors returned by SubmitDepositRequest.ValidateAll() if the designated
// constraints aren't met.
type SubmitDepositRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SubmitDepositRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SubmitDepositRequestMultiError) AllErrors() []error { return m }

// SubmitDepositRequestValidationError is the validation error returned by
// SubmitDepositRequest.Validate if the designated constraints aren't met.
type SubmitDepositRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SubmitDepositRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SubmitDepositRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SubmitDepositRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SubmitDepositRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SubmitDepositRequestValidationError) ErrorName() string {
	return "SubmitDepositRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SubmitDepositRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSubmitDepositRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SubmitDepositRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SubmitDepositRequestValidationError{}

// Validate checks the field values on SubmitDepositReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SubmitDepositReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SubmitDepositReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SubmitDepositReplyMultiError, or nil if none found.
func (m *SubmitDepositReply) ValidateAll() error {
	return m.validate(true)
}

func (m *SubmitDepositReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetResult()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SubmitDepositReplyValidationError{
					field:  "Result",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SubmitDepositReplyValidationError{
					field:  "Result",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetResult()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SubmitDepositReplyValidationError{
				field:  "Result",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SubmitDepositReplyMultiError(errors)
	}

	return nil
}

// SubmitDepositReplyMultiError is an error wrapping multiple validation errors
// returned by SubmitDepositReply.ValidateAll() if the designated constraints
// aren't met.
type SubmitDepositReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SubmitDepositReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SubmitDepositReplyMultiError) AllErrors() []error { return m }

// SubmitDepositReplyValidationError is the validation error returned by
// SubmitDepositReply.Validate if the designated constraints aren't met.
type SubmitDepositReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SubmitDepositReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SubmitDepositReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SubmitDepositReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SubmitDepositReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SubmitDepositReplyValidationError) ErrorName() string {
	return "SubmitDepositReplyValidationError"
}

// Error satisfies the builtin error interface
func (e SubmitDepositReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSubmitDepositReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SubmitDepositReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SubmitDepositReplyValidationError{}

// Validate checks the field values on ExpireTimeoutsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ExpireTimeoutsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ExpireTimeoutsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ExpireTimeoutsRequestMultiError, or nil if none found.
func (m *ExpireTimeoutsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ExpireTimeoutsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for NowUnix

	// no validation rules for Limit

	if len(errors) > 0 {
		return ExpireTimeoutsRequestMultiError(errors)
	}

	return nil
}

// ExpireTimeoutsRequestMultiError is an error wrapping multiple validation
// errors returned by ExpireTimeoutsRequest.ValidateAll() if the designated
// constraints aren't met.
type ExpireTimeoutsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ExpireTimeoutsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ExpireTimeoutsRequestMultiError) AllErrors() []error { return m }

// ExpireTimeoutsRequestValidationError is the validation error returned by
// ExpireTimeoutsRequest.Validate if the designated constraints aren't met.
type ExpireTimeoutsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExpireTimeoutsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExpireTimeoutsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExpireTimeoutsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExpireTimeoutsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExpireTimeoutsRequestValidationError) ErrorName() string {
	return "ExpireTimeoutsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ExpireTimeoutsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExpireTimeoutsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExpireTimeoutsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExpireTimeoutsRequestValidationError{}

// Validate checks the field values on ExpireTimeoutsReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ExpireTimeoutsReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ExpireTimeoutsReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ExpireTimeoutsReplyMultiError, or nil if none found.
func (m *ExpireTimeoutsReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ExpireTimeoutsReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for WaitingDeposits

	// no validation rules for LockedDeposits

	// no validation rules for Baskets

	if len(errors) > 0 {
		return ExpireTimeoutsReplyMultiError(errors)
	}

	return nil
}

// ExpireTimeoutsReplyMultiError is an error wrapping multiple validation
// errors returned by ExpireTimeoutsReply.ValidateAll() if the designated
// constraints aren't met.
type ExpireTimeoutsReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ExpireTimeoutsReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ExpireTimeoutsReplyMultiError) AllErrors() []error { return m }

// ExpireTimeoutsReplyValidationError is the validation error returned by
// ExpireTimeoutsReply.Validate if the designated constraints aren't met.
type ExpireTimeoutsReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExpireTimeoutsReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExpireTimeoutsReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExpireTimeoutsReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExpireTimeoutsReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExpireTimeoutsReplyValidationError) ErrorName() string {
	return "ExpireTimeoutsReplyValidationError"
}

// Error satisfies the builtin error interface
func (e ExpireTimeoutsReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExpireTimeoutsReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExpireTimeoutsReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExpireTimeoutsReplyValidationError{}

// Validate checks the field values on GetDepositRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetDepositRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetDepositRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetDepositRequestMultiError, or nil if none found.
func (m *GetDepositRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetDepositRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetDepositNo()) < 1 {
		err := GetDepositRequestValidationError{
			field:  "DepositNo",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetDepositRequestMultiError(errors)
	}

	return nil
}

// GetDepositRequestMultiError is an error wrapping multiple validation errors
// returned by GetDepositRequest.ValidateAll() if the designated constraints
// aren't met.
type GetDepositRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetDepositRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetDepositRequestMultiError) AllErrors() []error { return m }

// GetDepositRequestValidationError is the validation error returned by
// GetDepositRequest.Validate if the designated constraints aren't met.
type GetDepositRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetDepositRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetDepositRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetDepositRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetDepositRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetDepositRequestValidationError) ErrorName() string {
	return "GetDepositRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetDepositRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetDepositRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetDepositRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetDepositRequestValidationError{}

// Validate checks the field values on GetDepositReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetDepositReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetDepositReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetDepositReplyMultiError, or nil if none found.
func (m *GetDepositReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetDepositReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetDeposit()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetDepositReplyValidationError{
					field:  "Deposit",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetDepositReplyValidationError{
					field:  "Deposit",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDeposit()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetDepositReplyValidationError{
				field:  "Deposit",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetDepositReplyMultiError(errors)
	}

	return nil
}

// GetDepositReplyMultiError is an error wrapping multiple validation errors
// returned by GetDepositReply.ValidateAll() if the designated constraints
// aren't met.
type GetDepositReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetDepositReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetDepositReplyMultiError) AllErrors() []error { return m }

// GetDepositReplyValidationError is the validation error returned by
// GetDepositReply.Validate if the designated constraints aren't met.
type GetDepositReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetDepositReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetDepositReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetDepositReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetDepositReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetDepositReplyValidationError) ErrorName() string { return "GetDepositReplyValidationError" }

// Error satisfies the builtin error interface
func (e GetDepositReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetDepositReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetDepositReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetDepositReplyValidationError{}

// Validate checks the field values on GetBasketRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetBasketRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetBasketRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetBasketRequestMultiError, or nil if none found.
func (m *GetBasketRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetBasketRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetBasketNo()) < 1 {
		err := GetBasketRequestValidationError{
			field:  "BasketNo",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetBasketRequestMultiError(errors)
	}

	return nil
}

// GetBasketRequestMultiError is an error wrapping multiple validation errors
// returned by GetBasketRequest.ValidateAll() if the designated constraints
// aren't met.
type GetBasketRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetBasketRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetBasketRequestMultiError) AllErrors() []error { return m }

// GetBasketRequestValidationError is the validation error returned by
// GetBasketRequest.Validate if the designated constraints aren't met.
type GetBasketRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetBasketRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetBasketRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetBasketRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetBasketRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetBasketRequestValidationError) ErrorName() string { return "GetBasketRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetBasketRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetBasketRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetBasketRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetBasketRequestValidationError{}

// Validate checks the field values on GetBasketReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetBasketReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetBasketReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetBasketReplyMultiError,
// or nil if none found.
func (m *GetBasketReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetBasketReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetBasket()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetBasketReplyValidationError{
					field:  "Basket",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetBasketReplyValidationError{
					field:  "Basket",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetBasket()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetBasketReplyValidationError{
				field:  "Basket",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetBasketReplyMultiError(errors)
	}

	return nil
}

// GetBasketReplyMultiError is an error wrapping multiple validation errors
// returned by GetBasketReply.ValidateAll() if the designated constraints
// aren't met.
type GetBasketReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetBasketReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetBasketReplyMultiError) AllErrors() []error { return m }

// GetBasketReplyValidationError is the validation error returned by
// GetBasketReply.Validate if the designated constraints aren't met.
type GetBasketReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetBasketReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetBasketReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetBasketReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetBasketReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetBasketReplyValidationError) ErrorName() string { return "GetBasketReplyValidationError" }

// Error satisfies the builtin error interface
func (e GetBasketReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetBasketReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetBasketReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetBasketReplyValidationError{}

// Validate checks the field values on GetMatchRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetMatchRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetMatchRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetMatchRequestMultiError, or nil if none found.
func (m *GetMatchRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetMatchRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for MatchNo

	// no validation rules for BasketNo

	// no validation rules for WithdrawNo

	if len(errors) > 0 {
		return GetMatchRequestMultiError(errors)
	}

	return nil
}

// GetMatchRequestMultiError is an error wrapping multiple validation errors
// returned by GetMatchRequest.ValidateAll() if the designated constraints
// aren't met.
type GetMatchRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetMatchRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetMatchRequestMultiError) AllErrors() []error { return m }

// GetMatchRequestValidationError is the validation error returned by
// GetMatchRequest.Validate if the designated constraints aren't met.
type GetMatchRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetMatchRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetMatchRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetMatchRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetMatchRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetMatchRequestValidationError) ErrorName() string { return "GetMatchRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetMatchRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetMatchRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetMatchRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetMatchRequestValidationError{}

// Validate checks the field values on GetMatchReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetMatchReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetMatchReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetMatchReplyMultiError, or
// nil if none found.
func (m *GetMatchReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetMatchReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetMatch()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetMatchReplyValidationError{
					field:  "Match",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetMatchReplyValidationError{
					field:  "Match",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMatch()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetMatchReplyValidationError{
				field:  "Match",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetDeposits() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetMatchReplyValidationError{
						field:  fmt.Sprintf("Deposits[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetMatchReplyValidationError{
						field:  fmt.Sprintf("Deposits[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetMatchReplyValidationError{
					field:  fmt.Sprintf("Deposits[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetMatchReplyMultiError(errors)
	}

	return nil
}

// GetMatchReplyMultiError is an error wrapping multiple validation errors
// returned by GetMatchReply.ValidateAll() if the designated constraints
// aren't met.
type GetMatchReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetMatchReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetMatchReplyMultiError) AllErrors() []error { return m }

// GetMatchReplyValidationError is the validation error returned by
// GetMatchReply.Validate if the designated constraints aren't met.
type GetMatchReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetMatchReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetMatchReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetMatchReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetMatchReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetMatchReplyValidationError) ErrorName() string { return "GetMatchReplyValidationError" }

// Error satisfies the builtin error interface
func (e GetMatchReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetMatchReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetMatchReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetMatchReplyValidationError{}

// Validate checks the field values on CheckHealthRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CheckHealthRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CheckHealthRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CheckHealthRequestMultiError, or nil if none found.
func (m *CheckHealthRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CheckHealthRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return CheckHealthRequestMultiError(errors)
	}

	return nil
}

// CheckHealthRequestMultiError is an error wrapping multiple validation errors
// returned by CheckHealthRequest.ValidateAll() if the designated constraints
// aren't met.
type CheckHealthRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CheckHealthRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CheckHealthRequestMultiError) AllErrors() []error { return m }

// CheckHealthRequestValidationError is the validation error returned by
// CheckHealthRequest.Validate if the designated constraints aren't met.
type CheckHealthRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CheckHealthRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CheckHealthRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CheckHealthRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CheckHealthRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CheckHealthRequestValidationError) ErrorName() string {
	return "CheckHealthRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CheckHealthRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCheckHealthRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CheckHealthRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CheckHealthRequestValidationError{}

// Validate checks the field values on CheckHealthReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CheckHealthReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CheckHealthReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CheckHealthReplyMultiError, or nil if none found.
func (m *CheckHealthReply) ValidateAll() error {
	return m.validate(true)
}

func (m *CheckHealthReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Ok

	for idx, item := range m.GetComponents() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, CheckHealthReplyValidationError{
						field:  fmt.Sprintf("Components[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, CheckHealthReplyValidationError{
						field:  fmt.Sprintf("Components[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CheckHealthReplyValidationError{
					field:  fmt.Sprintf("Components[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return CheckHealthReplyMultiError(errors)
	}

	return nil
}

// CheckHealthReplyMultiError is an error wrapping multiple validation errors
// returned by CheckHealthReply.ValidateAll() if the designated constraints
// aren't met.
type CheckHealthReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CheckHealthReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CheckHealthReplyMultiError) AllErrors() []error { return m }

// CheckHealthReplyValidationError is the validation error returned by
// CheckHealthReply.Validate if the designated constraints aren't met.
type CheckHealthReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CheckHealthReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CheckHealthReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CheckHealthReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CheckHealthReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CheckHealthReplyValidationError) ErrorName() string { return "CheckHealthReplyValidationError" }

// Error satisfies the builtin error interface
func (e CheckHealthReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCheckHealthReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CheckHealthReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CheckHealthReplyValidationError{}

// Validate checks the field values on HealthComponent with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *HealthComponent) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HealthComponent with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// HealthComponentMultiError, or nil if none found.
func (m *HealthComponent) ValidateAll() error {
	return m.validate(true)
}

func (m *HealthComponent) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Ok

	// no validation rules for Message

	if len(errors) > 0 {
		return HealthComponentMultiError(errors)
	}

	return nil
}

// HealthComponentMultiError is an error wrapping multiple validation errors
// returned by HealthComponent.ValidateAll() if the designated constraints
// aren't met.
type HealthComponentMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HealthComponentMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HealthComponentMultiError) AllErrors() []error { return m }

// HealthComponentValidationError is the validation error returned by
// HealthComponent.Validate if the designated constraints aren't met.
type HealthComponentValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HealthComponentValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HealthComponentValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HealthComponentValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HealthComponentValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HealthComponentValidationError) ErrorName() string { return "HealthComponentValidationError" }

// Error satisfies the builtin error interface
func (e HealthComponentValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHealthComponent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HealthComponentValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HealthComponentValidationError{}

// Validate checks the field values on MatchResult with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *MatchResult) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MatchResult with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in MatchResultMultiError, or
// nil if none found.
func (m *MatchResult) ValidateAll() error {
	return m.validate(true)
}

func (m *MatchResult) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Matched

	// no validation rules for Attached

	// no validation rules for BasketNo

	// no validation rules for WithdrawNo

	// no validation rules for Channel

	// no validation rules for Currency

	// no validation rules for TargetAmount

	// no validation rules for MatchedAmount

	// no validation rules for ShortAmount

	// no validation rules for Pending

	// no validation rules for FailedReason

	if len(errors) > 0 {
		return MatchResultMultiError(errors)
	}

	return nil
}

// MatchResultMultiError is an error wrapping multiple validation errors
// returned by MatchResult.ValidateAll() if the designated constraints aren't met.
type MatchResultMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MatchResultMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MatchResultMultiError) AllErrors() []error { return m }

// MatchResultValidationError is the validation error returned by
// MatchResult.Validate if the designated constraints aren't met.
type MatchResultValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MatchResultValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MatchResultValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MatchResultValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MatchResultValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MatchResultValidationError) ErrorName() string { return "MatchResultValidationError" }

// Error satisfies the builtin error interface
func (e MatchResultValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMatchResult.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MatchResultValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MatchResultValidationError{}

// Validate checks the field values on DepositOrder with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DepositOrder) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DepositOrder with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DepositOrderMultiError, or
// nil if none found.
func (m *DepositOrder) ValidateAll() error {
	return m.validate(true)
}

func (m *DepositOrder) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DepositNo

	// no validation rules for MerchantId

	// no validation rules for Channel

	// no validation rules for Currency

	// no validation rules for Amount

	// no validation rules for Status

	if all {
		switch v := interface{}(m.GetExpireAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DepositOrderValidationError{
					field:  "ExpireAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DepositOrderValidationError{
					field:  "ExpireAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetExpireAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DepositOrderValidationError{
				field:  "ExpireAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for MatchedBasketNo

	// no validation rules for MatchNo

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DepositOrderValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DepositOrderValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DepositOrderValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DepositOrderValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DepositOrderValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DepositOrderValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return DepositOrderMultiError(errors)
	}

	return nil
}

// DepositOrderMultiError is an error wrapping multiple validation errors
// returned by DepositOrder.ValidateAll() if the designated constraints aren't met.
type DepositOrderMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DepositOrderMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DepositOrderMultiError) AllErrors() []error { return m }

// DepositOrderValidationError is the validation error returned by
// DepositOrder.Validate if the designated constraints aren't met.
type DepositOrderValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DepositOrderValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DepositOrderValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DepositOrderValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DepositOrderValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DepositOrderValidationError) ErrorName() string { return "DepositOrderValidationError" }

// Error satisfies the builtin error interface
func (e DepositOrderValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDepositOrder.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DepositOrderValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DepositOrderValidationError{}

// Validate checks the field values on WithdrawBasket with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *WithdrawBasket) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WithdrawBasket with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in WithdrawBasketMultiError,
// or nil if none found.
func (m *WithdrawBasket) ValidateAll() error {
	return m.validate(true)
}

func (m *WithdrawBasket) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for BasketNo

	// no validation rules for WithdrawNo

	// no validation rules for MerchantId

	// no validation rules for Channel

	// no validation rules for Currency

	// no validation rules for TargetAmount

	// no validation rules for CurrentAmount

	// no validation rules for Status

	if all {
		switch v := interface{}(m.GetExpireAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, WithdrawBasketValidationError{
					field:  "ExpireAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, WithdrawBasketValidationError{
					field:  "ExpireAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetExpireAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WithdrawBasketValidationError{
				field:  "ExpireAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Version

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, WithdrawBasketValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, WithdrawBasketValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WithdrawBasketValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, WithdrawBasketValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, WithdrawBasketValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WithdrawBasketValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return WithdrawBasketMultiError(errors)
	}

	return nil
}

// WithdrawBasketMultiError is an error wrapping multiple validation errors
// returned by WithdrawBasket.ValidateAll() if the designated constraints
// aren't met.
type WithdrawBasketMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WithdrawBasketMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WithdrawBasketMultiError) AllErrors() []error { return m }

// WithdrawBasketValidationError is the validation error returned by
// WithdrawBasket.Validate if the designated constraints aren't met.
type WithdrawBasketValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WithdrawBasketValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WithdrawBasketValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WithdrawBasketValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WithdrawBasketValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WithdrawBasketValidationError) ErrorName() string { return "WithdrawBasketValidationError" }

// Error satisfies the builtin error interface
func (e WithdrawBasketValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWithdrawBasket.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WithdrawBasketValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WithdrawBasketValidationError{}

// Validate checks the field values on MatchRecord with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *MatchRecord) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MatchRecord with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in MatchRecordMultiError, or
// nil if none found.
func (m *MatchRecord) ValidateAll() error {
	return m.validate(true)
}

func (m *MatchRecord) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for MatchNo

	// no validation rules for BasketNo

	// no validation rules for WithdrawNo

	// no validation rules for TargetAmount

	// no validation rules for MatchedAmount

	// no validation rules for ShortAmount

	// no validation rules for Channel

	// no validation rules for Currency

	// no validation rules for Status

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MatchRecordValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MatchRecordValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MatchRecordValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MatchRecordValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MatchRecordValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MatchRecordValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return MatchRecordMultiError(errors)
	}

	return nil
}

// MatchRecordMultiError is an error wrapping multiple validation errors
// returned by MatchRecord.ValidateAll() if the designated constraints aren't met.
type MatchRecordMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MatchRecordMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MatchRecordMultiError) AllErrors() []error { return m }

// MatchRecordValidationError is the validation error returned by
// MatchRecord.Validate if the designated constraints aren't met.
type MatchRecordValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MatchRecordValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MatchRecordValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MatchRecordValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MatchRecordValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MatchRecordValidationError) ErrorName() string { return "MatchRecordValidationError" }

// Error satisfies the builtin error interface
func (e MatchRecordValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMatchRecord.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MatchRecordValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MatchRecordValidationError{}

// Validate checks the field values on DepositEventMessage with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DepositEventMessage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DepositEventMessage with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DepositEventMessageMultiError, or nil if none found.
func (m *DepositEventMessage) ValidateAll() error {
	return m.validate(true)
}

func (m *DepositEventMessage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for EventId

	// no validation rules for Topic

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DepositEventMessageValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DepositEventMessageValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DepositEventMessageValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return DepositEventMessageMultiError(errors)
	}

	return nil
}

// DepositEventMessageMultiError is an error wrapping multiple validation
// errors returned by DepositEventMessage.ValidateAll() if the designated
// constraints aren't met.
type DepositEventMessageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DepositEventMessageMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DepositEventMessageMultiError) AllErrors() []error { return m }

// DepositEventMessageValidationError is the validation error returned by
// DepositEventMessage.Validate if the designated constraints aren't met.
type DepositEventMessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DepositEventMessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DepositEventMessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DepositEventMessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DepositEventMessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DepositEventMessageValidationError) ErrorName() string {
	return "DepositEventMessageValidationError"
}

// Error satisfies the builtin error interface
func (e DepositEventMessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDepositEventMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DepositEventMessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DepositEventMessageValidationError{}

// Validate checks the field values on WithdrawEventMessage with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *WithdrawEventMessage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WithdrawEventMessage with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// WithdrawEventMessageMultiError, or nil if none found.
func (m *WithdrawEventMessage) ValidateAll() error {
	return m.validate(true)
}

func (m *WithdrawEventMessage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for EventId

	// no validation rules for Topic

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, WithdrawEventMessageValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, WithdrawEventMessageValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WithdrawEventMessageValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return WithdrawEventMessageMultiError(errors)
	}

	return nil
}

// WithdrawEventMessageMultiError is an error wrapping multiple validation
// errors returned by WithdrawEventMessage.ValidateAll() if the designated
// constraints aren't met.
type WithdrawEventMessageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WithdrawEventMessageMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WithdrawEventMessageMultiError) AllErrors() []error { return m }

// WithdrawEventMessageValidationError is the validation error returned by
// WithdrawEventMessage.Validate if the designated constraints aren't met.
type WithdrawEventMessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WithdrawEventMessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WithdrawEventMessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WithdrawEventMessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WithdrawEventMessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WithdrawEventMessageValidationError) ErrorName() string {
	return "WithdrawEventMessageValidationError"
}

// Error satisfies the builtin error interface
func (e WithdrawEventMessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWithdrawEventMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WithdrawEventMessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WithdrawEventMessageValidationError{}

// Validate checks the field values on MatchRecordDeposit with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *MatchRecordDeposit) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MatchRecordDeposit with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MatchRecordDepositMultiError, or nil if none found.
func (m *MatchRecordDeposit) ValidateAll() error {
	return m.validate(true)
}

func (m *MatchRecordDeposit) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for MatchNo

	// no validation rules for WithdrawNo

	// no validation rules for DepositNo

	// no validation rules for Amount

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MatchRecordDepositValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MatchRecordDepositValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MatchRecordDepositValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return MatchRecordDepositMultiError(errors)
	}

	return nil
}

// MatchRecordDepositMultiError is an error wrapping multiple validation errors
// returned by MatchRecordDeposit.ValidateAll() if the designated constraints
// aren't met.
type MatchRecordDepositMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MatchRecordDepositMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MatchRecordDepositMultiError) AllErrors() []error { return m }

// MatchRecordDepositValidationError is the validation error returned by
// MatchRecordDeposit.Validate if the designated constraints aren't met.
type MatchRecordDepositValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MatchRecordDepositValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MatchRecordDepositValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MatchRecordDepositValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MatchRecordDepositValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MatchRecordDepositValidationError) ErrorName() string {
	return "MatchRecordDepositValidationError"
}

// Error satisfies the builtin error interface
func (e MatchRecordDepositValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMatchRecordDeposit.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MatchRecordDepositValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MatchRecordDepositValidationError{}
