// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "time"

const TableNameBasketDeposit = "basket_deposit"

// BasketDeposit 篮子入金明细
type BasketDeposit struct {
	ID         int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:自增主键" json:"id"`                                     // 自增主键
	BasketNo   string    `gorm:"column:basket_no;type:varchar(64);not null;index:idx_basket_no,priority:1;comment:篮子单号" json:"basketNo"`         // 篮子单号
	WithdrawNo string    `gorm:"column:withdraw_no;type:varchar(64);not null;index:idx_withdraw_no,priority:1;comment:出金单号" json:"withdrawNo"`   // 出金单号
	DepositNo  string    `gorm:"column:deposit_no;type:varchar(64);not null;uniqueIndex:uk_deposit_no,priority:1;comment:入金单号" json:"depositNo"` // 入金单号
	Amount     int64     `gorm:"column:amount;type:bigint;not null;comment:入金金额，最小货币单位" json:"amount"`                                           // 入金金额，最小货币单位
	Status     int32     `gorm:"column:status;type:tinyint;not null;comment:状态：1已挂入 2已撮合 3已释放" json:"status"`                                    // 状态：1已挂入 2已撮合 3已释放
	CreatedAt  time.Time `gorm:"column:created_at;type:datetime(3);not null;default:CURRENT_TIMESTAMP(3);comment:创建时间" json:"createdAt"`         // 创建时间
	UpdatedAt  time.Time `gorm:"column:updated_at;type:datetime(3);not null;default:CURRENT_TIMESTAMP(3);comment:更新时间" json:"updatedAt"`         // 更新时间
}

// TableName 返回 BasketDeposit 对应的表名。
func (BasketDeposit) TableName() string {
	return TableNameBasketDeposit
}
