// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "time"

const TableNameEventInbox = "match_event_inbox"

// EventInbox RocketMQ 消费幂等表
type EventInbox struct {
	ID        int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:自增主键" json:"id"`                                                         // 自增主键
	EventID   string    `gorm:"column:event_id;type:varchar(128);not null;uniqueIndex:uk_event_id,priority:1;comment:事件唯一ID" json:"eventId"`                        // 事件唯一ID
	Topic     string    `gorm:"column:topic;type:varchar(128);not null;comment:RocketMQ topic" json:"topic"`                                                        // RocketMQ 主题
	BizNo     string    `gorm:"column:biz_no;type:varchar(64);not null;index:idx_biz_no,priority:1;comment:业务单号" json:"bizNo"`                                      // 业务单号
	Status    int32     `gorm:"column:status;type:tinyint;not null;index:idx_status,priority:1;comment:状态：1处理中 2成功 3失败" json:"status"`                              // 状态
	ErrorMsg  string    `gorm:"column:error_msg;type:varchar(512);comment:错误信息" json:"errorMsg"`                                                                    // 错误信息
	CreatedAt time.Time `gorm:"column:created_at;type:datetime(3);not null;default:CURRENT_TIMESTAMP(3);comment:创建时间" json:"createdAt"`                             // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;type:datetime(3);not null;default:CURRENT_TIMESTAMP(3);index:idx_status,priority:2;comment:更新时间" json:"updatedAt"` // 更新时间
}

// TableName 返回 EventInbox 对应的表名。
func (EventInbox) TableName() string {
	return TableNameEventInbox
}
