// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "time"

const TableNameMatchRecord = "match_record"
const TableNameMatchRecordDeposit = "match_record_deposit"

// MatchRecord 撮合结果
type MatchRecord struct {
	ID            int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:自增主键" json:"id"`                                                         // 自增主键
	MatchNo       string    `gorm:"column:match_no;type:varchar(64);not null;uniqueIndex:uk_match_no,priority:1;comment:撮合结果单号" json:"matchNo"`                         // 撮合结果单号
	BasketNo      string    `gorm:"column:basket_no;type:varchar(64);not null;uniqueIndex:uk_basket_no,priority:1;comment:篮子单号" json:"basketNo"`                        // 篮子单号
	WithdrawNo    string    `gorm:"column:withdraw_no;type:varchar(64);not null;index:idx_withdraw_no,priority:1;comment:出金单号" json:"withdrawNo"`                       // 出金单号
	TargetAmount  int64     `gorm:"column:target_amount;type:bigint;not null;comment:出金目标金额" json:"targetAmount"`                                                       // 出金目标金额
	MatchedAmount int64     `gorm:"column:matched_amount;type:bigint;not null;comment:实际撮合金额" json:"matchedAmount"`                                                     // 实际撮合金额
	ShortAmount   int64     `gorm:"column:short_amount;type:bigint;not null;default:0;comment:少发金额" json:"shortAmount"`                                                 // 少发金额
	Channel       string    `gorm:"column:channel;type:varchar(32);not null;comment:支付渠道" json:"channel"`                                                               // 支付渠道
	Currency      string    `gorm:"column:currency;type:varchar(16);not null;comment:币种" json:"currency"`                                                               // 币种
	Status        int32     `gorm:"column:status;type:tinyint;not null;index:idx_status,priority:1;comment:状态：1已创建 2已发送支付 3支付中 4成功 5失败" json:"status"`                  // 状态
	CreatedAt     time.Time `gorm:"column:created_at;type:datetime(3);not null;default:CURRENT_TIMESTAMP(3);index:idx_status,priority:2;comment:创建时间" json:"createdAt"` // 创建时间
	UpdatedAt     time.Time `gorm:"column:updated_at;type:datetime(3);not null;default:CURRENT_TIMESTAMP(3);comment:更新时间" json:"updatedAt"`                             // 更新时间
}

// TableName 返回 MatchRecord 对应的表名。
func (MatchRecord) TableName() string {
	return TableNameMatchRecord
}

// MatchRecordDeposit 撮合结果入金明细
type MatchRecordDeposit struct {
	ID         int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:自增主键" json:"id"`                                     // 自增主键
	MatchNo    string    `gorm:"column:match_no;type:varchar(64);not null;index:idx_match_no,priority:1;comment:撮合结果单号" json:"matchNo"`          // 撮合结果单号
	WithdrawNo string    `gorm:"column:withdraw_no;type:varchar(64);not null;index:idx_withdraw_no,priority:1;comment:出金单号" json:"withdrawNo"`   // 出金单号
	DepositNo  string    `gorm:"column:deposit_no;type:varchar(64);not null;uniqueIndex:uk_deposit_no,priority:1;comment:入金单号" json:"depositNo"` // 入金单号
	Amount     int64     `gorm:"column:amount;type:bigint;not null;comment:入金金额，最小货币单位" json:"amount"`                                           // 入金金额，最小货币单位
	CreatedAt  time.Time `gorm:"column:created_at;type:datetime(3);not null;default:CURRENT_TIMESTAMP(3);comment:创建时间" json:"createdAt"`         // 创建时间
}

// TableName 返回 MatchRecordDeposit 对应的表名。
func (MatchRecordDeposit) TableName() string {
	return TableNameMatchRecordDeposit
}
