// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "time"

const TableNameWithdrawBasket = "withdraw_basket"

// WithdrawBasket 出金撮合篮子
type WithdrawBasket struct {
	ID            int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:自增主键" json:"id"`                                                                 // 自增主键
	BasketNo      string    `gorm:"column:basket_no;type:varchar(64);not null;uniqueIndex:uk_basket_no,priority:1;comment:篮子单号" json:"basketNo"`                                // 篮子单号
	WithdrawNo    string    `gorm:"column:withdraw_no;type:varchar(64);not null;uniqueIndex:uk_withdraw_no,priority:1;comment:出金单号" json:"withdrawNo"`                          // 出金单号
	MerchantID    int64     `gorm:"column:merchant_id;type:bigint;not null;comment:商户ID" json:"merchantId"`                                                                     // 商户ID
	Channel       string    `gorm:"column:channel;type:varchar(32);not null;index:idx_pool,priority:1;index:idx_need_expr,priority:1;comment:支付渠道" json:"channel"`              // 支付渠道
	Currency      string    `gorm:"column:currency;type:varchar(16);not null;index:idx_pool,priority:2;index:idx_need_expr,priority:2;comment:币种" json:"currency"`              // 币种
	TargetAmount  int64     `gorm:"column:target_amount;type:bigint;not null;index:idx_need_expr,priority:4;comment:出金目标金额" json:"targetAmount"`                                // 出金目标金额
	CurrentAmount int64     `gorm:"column:current_amount;type:bigint;not null;default:0;index:idx_need_expr,priority:5;comment:已凑金额" json:"currentAmount"`                      // 已凑金额
	Status        int32     `gorm:"column:status;type:tinyint;not null;index:idx_pool,priority:3;index:idx_need_expr,priority:3;comment:状态：1等待 2锁定 3已撮合 4过期 5取消" json:"status"` // 状态
	ExpireAt      time.Time `gorm:"column:expire_at;type:datetime(3);not null;index:idx_pool,priority:4;comment:出金过期时间" json:"expireAt"`                                        // 出金过期时间
	Version       int64     `gorm:"column:version;type:bigint;not null;default:0;comment:乐观锁版本" json:"version"`                                                                 // 乐观锁版本
	CreatedAt     time.Time `gorm:"column:created_at;type:datetime(3);not null;default:CURRENT_TIMESTAMP(3);comment:创建时间" json:"createdAt"`                                     // 创建时间
	UpdatedAt     time.Time `gorm:"column:updated_at;type:datetime(3);not null;default:CURRENT_TIMESTAMP(3);index:idx_updated_at,priority:1;comment:更新时间" json:"updatedAt"`     // 更新时间
}

// TableName 返回 WithdrawBasket 对应的表名。
func (WithdrawBasket) TableName() string {
	return TableNameWithdrawBasket
}

// NeedAmount 返回篮子还差多少钱才能达到出金目标。
func (b *WithdrawBasket) NeedAmount() int64 {
	need := b.TargetAmount - b.CurrentAmount
	if need < 0 {
		return 0
	}
	return need
}

// RoomAmount 返回篮子当前最多还能接收多少钱。
func (b *WithdrawBasket) RoomAmount() int64 {
	room := b.TargetAmount - b.CurrentAmount
	if room < 0 {
		return 0
	}
	return room
}

// CanAccept 判断一笔入金是否可以先放入这个篮子。
func (b *WithdrawBasket) CanAccept(amount int64) bool {
	return b.Status == StatusWaiting && amount <= b.RoomAmount()
}

// CanComplete 判断一笔入金放入后，是否可以让篮子直接撮合成功。
func (b *WithdrawBasket) CanComplete(amount int64) bool {
	next := b.CurrentAmount + amount
	return b.Status == StatusWaiting &&
		next == b.TargetAmount
}
